const Apify = require("apify");
const {
    handleStart,
    handleList,
    handleDetail,
    handleDirector,
    handleSitemap,
} = require("./src/routes");
const Mongo = require("./src/MongoDB/mongodb");
const { RequestQueue } = require("apify");
DEBUG = true;
const {
    utils: { log },
} = Apify;
const DEBUG_LEVEL = true;
const local_dev = false

const { urls } = require('./list')


function logInfo(message) {
    if (DEBUG) {
        console.log(message);
    }
}

exports.stats = {
    contact_phone_scrapped: 0,
    contact_web_scrapped: 0,
    contact_email_scrapped: 0,
    database_added: 0,
    register_page_hit: 0,
    session_retired: 0,
    time_to_scrap: [],
};

exports.scrapDirectors = false;

exports.mongo = new Mongo();

Apify.main(async () => {
    let input = await Apify.getInput();

    
    // let proxyConfig = {
    //     useApifyProxy: true,
    //     apifyProxyGroups: ["RESIDENTIAL"],
    //     apifyProxyCountry: "IE",
    // };

    // logInfo(proxyConfig);

    // let proxyConfiguration
    // let proxyConfiguration = await Apify.createProxyConfiguration(
    //     // proxyConfig
    // );
    let requestList
    if(local_dev){

    requestList =  await Apify.openRequestList("start-urls", [
        // 'https://www.companywall.hr/tvrtka/central-europe-trade-jdoo/MMIB1DCC',
        // 'https://www.companywall.hr/tvrtka/brenner-corporated-jdoo/MMIB1lE0',
        // 'https://www.companywall.hr/tvrtka/maja-ugostiteljstvo-j-d-o-o-u-stecaju/MMIB1puq',
        // 'https://www.companywall.hr/tvrtka/mb-elektrika-jdoo/MMIB1toD',
        // 'https://www.companywall.hr/tvrtka/filla-food-jdoo/MMIB1zhY',
        // 'https://www.companywall.hr/tvrtka/auto-jurica-jdoo/MMIBE5cR',
        // 'https://www.companywall.hr/tvrtka/sistem-dizajn-jdoo/MMIBEBWC',
        // 'https://www.companywall.hr/tvrtka/consilium-septem-doo/MMxUtPV0',
        // 'https://www.companywall.hr/tvrtka/laser-satovic-jdoo-u-likvidaciji/MMIBEIR0',
        // 'https://www.companywall.hr/tvrtka/durec-ugostiteljstvo-jdoo/MMIBEPGq',
        // 'https://www.companywall.hr/tvrtka/metro-living-doo/MMIBEU3D',
        // 'https://www.companywall.hr/tvrtka/c2t-business-doo/MMIBEXyY',
        // 'https://www.companywall.hr/tvrtka/medic-metal-doo/MMIBEbrR',
        // 'https://www.companywall.hr/tvrtka/limeri-uniform-doo/MMIBEfkC',
        // 'https://www.companywall.hr/tvrtka/valvula-doo/MMIBEje0',
        // 'https://www.companywall.hr/tvrtka/kreso-prijevoz-doo/MMIBEoJq',
        // 'https://www.companywall.hr/tvrtka/format-b-doo/MMIBEQSD',
        // 'https://www.companywall.hr/tvrtka/izvan-okvira-d-o-o/MMIBEyKY',
        // 'https://www.companywall.hr/tvrtka/batuhan-doo-u-stecaju/MMxUtUOq',
        // 'https://www.companywall.hr/tvrtka/mcl-audio-doo/MMIB5E9R',
        // 'https://www.companywall.hr/tvrtka/eliza-doo/MMIB59xC',
        // 'https://www.companywall.hr/tvrtka/non-plus-ultra-doo/MMIB5Gt0',
        // 'https://www.companywall.hr/tvrtka/duo-interijeri-doo/MMIB52Nq',
        // 'https://www.companywall.hr/tvrtka/krovogradnja-doo/MMIB5SgD',
        // 'https://www.companywall.hr/tvrtka/lp-services-j-d-o-o/MMIB5WaY',
        // 'https://www.companywall.hr/tvrtka/project-63-doo/MMIB5a4R',
        // 'https://www.companywall.hr/tvrtka/microbug-doo/MMIB5eOC',
        // 'https://www.companywall.hr/tvrtka/robot-22-doo/MMIB5iF0',
        // 'https://www.companywall.hr/tvrtka/rekab-2512-jdoo/MMIB5nEq',
        // 'https://www.companywall.hr/tvrtka/galimed-doo/MM9JVuC',
        // 'https://www.companywall.hr/tvrtka/dogan-septem-doo/MMxUtJFD',
        // 'https://www.companywall.hr/tvrtka/journal-jdoo/MMIB5rvD',
        // 'https://www.companywall.hr/tvrtka/icc-multiservis-doo/MMIB5vpY',
        // 'https://www.companywall.hr/tvrtka/taktika-jdoo/MMIB3xiR',
        // 'https://www.companywall.hr/tvrtka/eae-business-doo/MMIB37dC',
        // 'https://www.companywall.hr/tvrtka/til-plast-jdoo/MMIB3FX0',
        // 'https://www.companywall.hr/tvrtka/ima-mate-doo/MMIB3LRq',
        // 'https://www.companywall.hr/tvrtka/the-office-2a-jdoo/MMIB36HD',
        // 'https://www.companywall.hr/tvrtka/rest-doo/MMIB3V7Y',
        // 'https://www.companywall.hr/tvrtka/jedina-nekretnina-doo/MMIB3YzR',
        // 'https://www.companywall.hr/tvrtka/bart-solutions-doo/MMIB3dsC',
        // 'https://www.companywall.hr/tvrtka/kubak-stil-doo/MMxUtc5Y',
        // 'https://www.companywall.hr/tvrtka/adriatic-sailing-doo/MMIB3Dl0',
        // 'https://www.companywall.hr/tvrtka/principium-bretia--jdoo/MMIB3leq',
        // 'https://www.companywall.hr/tvrtka/mb-trade-jdoo/MMIB3qYD',
        // 'https://www.companywall.hr/tvrtka/milk--honey-doo/MMIB3uTY',
        // 'https://www.companywall.hr/tvrtka/contact-doo/MMIB70LR',
        // 'https://www.companywall.hr/tvrtka/just-chocolate-jdoo/MMIB73BC',
        // 'https://www.companywall.hr/tvrtka/taxi-savica-jdoo/MMIB7C10',
        // 'https://www.companywall.hr/tvrtka/bitmedix-jdoo/MMIB7Itq',
        // 'https://www.companywall.hr/tvrtka/gazela-sesvete-doo-u-likvidaciji/MMxUtfwR',
        // 'https://www.companywall.hr/tvrtka/ladental-doo/MMIB7JbR',
        // 'https://www.companywall.hr/tvrtka/bonil-doo/MMIB7cVC',
        // 'https://www.companywall.hr/tvrtka/arnaut-doo-u-stecaju/MMIB7gP0',
        // 'https://www.companywall.hr/tvrtka/ideas--solutions-doo/MMIB7kFq',
        // 'https://www.companywall.hr/tvrtka/brkic-grupa-doo/MMIB7p5D',
        // 'https://www.companywall.hr/tvrtka/hedra-d-o-o/MMIB7QwY',
        // 'https://www.companywall.hr/tvrtka/kali-trans-d-o-o/MMIB7yqR',
        // 'https://www.companywall.hr/tvrtka/adri-konzalting-d-o-o/MMIBAEjC',
        // 'https://www.companywall.hr/tvrtka/vsd-group-doo/MMIBA980',
        // 'https://www.companywall.hr/tvrtka/marov-d-o-o-u-stecaju/MMIBAHXq',
        // 'https://www.companywall.hr/tvrtka/martinko-mont-doo/MMxUtjqC',
        // 'https://www.companywall.hr/tvrtka/dms-d-o-o/MMIBAO6D',
        // 'https://www.companywall.hr/tvrtka/hb-global-d-o-o/MMIBATIY',
        // 'https://www.companywall.hr/tvrtka/roso-doo/MMIBAXAR',
        // 'https://www.companywall.hr/tvrtka/happy-world-today-doo/MMIBAb0C',
        // 'https://www.companywall.hr/tvrtka/svilena-latica-doo/MMIBAeQ0',
        // 'https://www.companywall.hr/tvrtka/poljoprivredna-ljekarna-vodice-doo/MMIBAilq',
        // 'https://www.companywall.hr/tvrtka/kosirina-domicil-doo/MMIBAnfD',
        // 'https://www.companywall.hr/tvrtka/ai-systems-doo/MMIBAsZY',
        // 'https://www.companywall.hr/tvrtka/deniva-doo/MMIBAwUR',
        // 'https://www.companywall.hr/tvrtka/parketi-kala-jdoo/MMIB912C',
        // 'https://www.companywall.hr/tvrtka/lateramen-doo/MMxUtoj0',
        // 'https://www.companywall.hr/tvrtka/image-making-company-doo/MMIB9AC0',
        // 'https://www.companywall.hr/tvrtka/crib-consulting-international-doo/MMIB9G1q',
        // 'https://www.companywall.hr/tvrtka/versus-solutions-doo/MMIB9LuD',
        // 'https://www.companywall.hr/tvrtka/medic-jdoo/MMIB96oY',
        // 'https://www.companywall.hr/tvrtka/agro-ivanka-jdoo-u-stecaju/MMIB9VhR',
        // 'https://www.companywall.hr/tvrtka/zidani-vrtovi-doo/MMIB9ZcC',
        // 'https://www.companywall.hr/tvrtka/js-jdoo-u-stecaju/MMIB98W0',
        // 'https://www.companywall.hr/tvrtka/ml--partners-doo-u-stecaju/MMIB9hPq',
        // 'https://www.companywall.hr/tvrtka/total-art-jdoo/MMIB9NGD',
        // 'https://www.companywall.hr/tvrtka/chapter-four-doo/MMIB9r3Y',
        // 'https://www.companywall.hr/tvrtka/procat-i-gastro-doo-u-stecaju/MMxUtQdq',
        // 'https://www.companywall.hr/tvrtka/dekagon-jdoo/MMIB9uyR',
        // 'https://www.companywall.hr/tvrtka/b-b-protect-jdoo/MMIBB0rC',
        // 'https://www.companywall.hr/tvrtka/mp-prijevoz-jdoo-u-stecaju/MMIBB3k0',
        // 'https://www.companywall.hr/tvrtka/kaokakao-global-doo/MMIBBC8q',
        // 'https://www.companywall.hr/tvrtka/reinforce-doo/MMIBBKJD',
        // 'https://www.companywall.hr/tvrtka/kamelija-j-d-o-o-u-stecaju/MMIBBRSY',
        // 'https://www.companywall.hr/tvrtka/delibero-doo/MMIBB4KR',
        // 'https://www.companywall.hr/tvrtka/essential-complexity-doo/MMIBBY9C',
        // 'https://www.companywall.hr/tvrtka/kreisel--jdoo-u-stecaju/MMIBBdx0',
        // 'https://www.companywall.hr/tvrtka/ccf-yachts--cruise-ships-jdoo/MMIBBgQq',
        // 'https://www.companywall.hr/tvrtka/mali-grunt-doo/MMxUtyXD',
        // 'https://www.companywall.hr/tvrtka/t-film-doo/MMIBBkND',
        // 'https://www.companywall.hr/tvrtka/orion-sport-jdoo/MMIBBpgY',
        // 'https://www.companywall.hr/tvrtka/anoval-zastupanja-doo/MMIBBtaR',
        // 'https://www.companywall.hr/tvrtka/sino-united-data-technology-doo/MMIBBz4C',
        // 'https://www.companywall.hr/tvrtka/senad-bedic-jdoo/MMIBC5O0',
        // 'https://www.companywall.hr/tvrtka/galekovic-gradnja-jdoo/MMIBCBCq',
        // 'https://www.companywall.hr/tvrtka/sm-any-jdoo/MMIBCIED',
        // 'https://www.companywall.hr/tvrtka/zavoreo-jdoo-u-likvidaciji/MMIBCOvY',
        // 'https://www.companywall.hr/tvrtka/hvar-sailing-jdoo/MMIBCTpR',
        // 'https://www.companywall.hr/tvrtka/manuel-gradnja-jdoo/MMIBCXiC',
        // 'https://www.companywall.hr/tvrtka/petecin-doo/MMxUuE6Y',
        // 'https://www.companywall.hr/tvrtka/tim-vuksic-jdoo/MMIBCbd0',
        // 'https://www.companywall.hr/tvrtka/skoj-jdoo-u-stecaju/MMIBCfWq',
        // 'https://www.companywall.hr/tvrtka/red-point-jdoo/MMIBCjRD',
        // 'https://www.companywall.hr/tvrtka/kvarner-jdoo/MMIBCoHY',
        // 'https://www.companywall.hr/tvrtka/kapak-jdoo/MMIBCQ7R',
        // 'https://www.companywall.hr/tvrtka/lazare-jdoo/MMIBCwzC',
        // 'https://www.companywall.hr/tvrtka/tj-pivnica-stubica-jdoo/MMIBF1s0',
        // 'https://www.companywall.hr/tvrtka/503-agency-jdoo/MMIBFAkq',
        // 'https://www.companywall.hr/tvrtka/ddss-grupa-doo/MMIBFGeD',
        // 'https://www.companywall.hr/tvrtka/provansa-jdoo/MMIBF2YY',
        // 'https://www.companywall.hr/tvrtka/marflor-doo/MMxUu9IR',
        // 'https://www.companywall.hr/tvrtka/lk-leljak-projekti-jdoo/MMIBFSTR',
        // 'https://www.companywall.hr/tvrtka/anea-365-jdoo/MMIBFWLC',
        // 'https://www.companywall.hr/tvrtka/nardus-beauty-jdoo/MMIBFaB0',
        // 'https://www.companywall.hr/tvrtka/gamacommerce-jdoo/MMIBFexq',
        // 'https://www.companywall.hr/tvrtka/stocarsko-poljoprivredna-zadruga-krajina-biokovo/MMIBFhtD',
        // 'https://www.companywall.hr/tvrtka/mini-drive-jdoo-u-likvidaciji/MMIBFNnY',
        // 'https://www.companywall.hr/tvrtka/drveni-most-jdoo/MMIBFrDR',
        // 'https://www.companywall.hr/tvrtka/gubasevo-art-jdoo/MMIBFvbC',
        // 'https://www.companywall.hr/tvrtka/apm-expres-jdoo-u-stecaju/MMIBGxV0',
        // 'https://www.companywall.hr/tvrtka/soboslikarski-i-licilacki-radovi-maric-jdoo/MMIBG7Oq',
        // 'https://www.companywall.hr/tvrtka/vugi-cat-doo-u-stecaju/MMxUuHAC',
        // 'https://www.companywall.hr/tvrtka/hibis-stedionica-dd/MMIBGFFD',
        // 'https://www.companywall.hr/tvrtka/proservis-doo/MMIBGL5Y',
        // 'https://www.companywall.hr/tvrtka/septem-clasis--doo/MMIBGRwR',
        // 'https://www.companywall.hr/tvrtka/ca-ba-d-o-o/MMIBG4qC',
        // 'https://www.companywall.hr/tvrtka/lkw-tomic-d-o-o/MMIBGYj0',
        // 'https://www.companywall.hr/tvrtka/metal-block-doo-u-stecaju/MMIBGddq',
        // 'https://www.companywall.hr/tvrtka/looking-naval-doo/MMIBGDXD',
        // 'https://www.companywall.hr/tvrtka/bulfon-doo/MMIBGl6Y',
        // 'https://www.companywall.hr/tvrtka/dalmatinske-sume-doo/MMIBGqIR',
        // 'https://www.companywall.hr/tvrtka/izoart-doo/MMIBGuAC',
        // 'https://www.companywall.hr/tvrtka/tim-bolje-doo/MM9JZo0',
        // 'https://www.companywall.hr/tvrtka/kapra-d-o-o-u-stecaju/MMxUuO00',
        // 'https://www.companywall.hr/tvrtka/sui-generis-doo/MMIBH000',
        // 'https://www.companywall.hr/tvrtka/zmajska-posla-doo/MMIBH5sq',
        // 'https://www.companywall.hr/tvrtka/mandarin-experts-doo/MMIBHBlD',
        // 'https://www.companywall.hr/tvrtka/struja-sisak-doo/MMIBHIfY',
        // 'https://www.companywall.hr/tvrtka/cove-cissa-doo/MMIBHPZR',
        // 'https://www.companywall.hr/tvrtka/pentek-turist-doo-u-stecaju/MMIBHUUC',
        // 'https://www.companywall.hr/tvrtka/gt-gigavat-doo/MMIBHJ20',
        // 'https://www.companywall.hr/tvrtka/domaci-radio-jdoo/MMIBHcBq',
        // 'https://www.companywall.hr/tvrtka/sime-jdoo/MMIBHg1D',
        // 'https://www.companywall.hr/tvrtka/simmeo-jdoo/MMIBHjuY',
        // 'https://www.companywall.hr/tvrtka/narval-d-o-o/MMxUuSsq',
        // 'https://www.companywall.hr/tvrtka/bozic-gradnja-jdoo/MMIBHooR',
        // 'https://www.companywall.hr/tvrtka/mialorena-jdoo/MMIBHQhC',
        // 'https://www.companywall.hr/tvrtka/tancsa-jdoo-u-stecaju/MMIBHyc0',
        // 'https://www.companywall.hr/tvrtka/b--k-jdoo/MMIBIEVq',
        // 'https://www.companywall.hr/tvrtka/panker-usluge-jdoo/MMIBI9PD',
        // 'https://www.companywall.hr/tvrtka/di-no-jdoo-u-stecaju/MMIBIHGY',
        // 'https://www.companywall.hr/tvrtka/foodtech-doo-u-stecaju/MMIBIO3R',
        // 'https://www.companywall.hr/tvrtka/team-best-jdoo/MMIBISyC',
        // 'https://www.companywall.hr/tvrtka/la-trattoria-jdoo-u-stecaju/MMIBIWr0',
        // 'https://www.companywall.hr/tvrtka/eco-code-doo/MMIBIajq',
        // 'https://www.companywall.hr/tvrtka/retriver-doo/MMxUuWlD',
        // 'https://www.companywall.hr/tvrtka/mijumani-j-d-o-o/MMIBIe8D',
        // 'https://www.companywall.hr/tvrtka/cukarikafe-j-d-o-o/MMIBIiJY',
        // 'https://www.companywall.hr/tvrtka/alija-ab-j-d-o-o-u-stecaju/MMIBInSR',
        // 'https://www.companywall.hr/tvrtka/oaza-beach-j-d-o-o/MMIBIsKC',
        // 'https://www.companywall.hr/tvrtka/gezim-j-d-o-o-u-stecaju/MMIBIw90',
        // 'https://www.companywall.hr/tvrtka/samo-spiza-jdoo/MMIBK10q',
        // 'https://www.companywall.hr/tvrtka/dobar-zalogaj-jdoo/MMIBK7QD',
        // 'https://www.companywall.hr/tvrtka/iva-pazanin-jdoo/MMIBKFNY',
        // 'https://www.companywall.hr/tvrtka/paus-charter-doo/MMIBKLgR',
        // 'https://www.companywall.hr/tvrtka/laminat-jdoo-u-likvidaciji/MMIBK6aC',
        // 'https://www.companywall.hr/tvrtka/jugis-doo-u-stecaju/MMxUuafY',
        // 'https://www.companywall.hr/tvrtka/mit-stil-jdoo/MMIBKV40',
        // 'https://www.companywall.hr/tvrtka/pozitiva-food-jdoo/MMIBKZ2q',
        // 'https://www.companywall.hr/tvrtka/hiperion-jdoo-u-stecaju/MMIBK8CD',
        // 'https://www.companywall.hr/tvrtka/carvalek-jdoo-u-stecaju/MMIBKhEY',
        // 'https://www.companywall.hr/tvrtka/stone-house-lodge-jdoo/MMIBKlvR',
        // 'https://www.companywall.hr/tvrtka/beauty-by-dex-jdoo/MMIBKqpC',
        // 'https://www.companywall.hr/tvrtka/posh-trade-jdoo/MMIBKui0',
        // 'https://www.companywall.hr/tvrtka/zani-rent-jdoo-u-stecaju/MMIBL0cq',
        // 'https://www.companywall.hr/tvrtka/dg-ugostiteljstvo-jdoo/MMIBL3WD',
        // 'https://www.companywall.hr/tvrtka/malukavi-jdoo/MMIBLCRY',
        // 'https://www.companywall.hr/tvrtka/grafo-print-doo-u-stecaju/MMxUueZR',
        // 'https://www.companywall.hr/tvrtka/bim-team-doo/MMIBLKHR',
        // 'https://www.companywall.hr/tvrtka/duga-jdi-home-jdoo/MMIBLR7C',
        // 'https://www.companywall.hr/tvrtka/uciliste-abc-strani-jezici/MMIBLUz0',
        // 'https://www.companywall.hr/tvrtka/frizerski-salon-freeze-jdoo-u-likvidaciji/MMIBLJrq',
        // 'https://www.companywall.hr/tvrtka/manuel-sport-doo/MMIBLckD',
        // 'https://www.companywall.hr/tvrtka/zele-gradnja-jdoo/MMIBLgeY',
        // 'https://www.companywall.hr/tvrtka/mango-voce-doo/MMIBLkYR',
        // 'https://www.companywall.hr/tvrtka/all-seasons-hit-jdoo/MMIBLpTC',
        // 'https://www.companywall.hr/tvrtka/santarel-jdoo/MMIBLtL0',
        // 'https://www.companywall.hr/tvrtka/assiduus-jdoo/MMIBLz9q',
        // 'https://www.companywall.hr/tvrtka/adriatic-sub-d-o-o/MMxUuiUC',
        // 'https://www.companywall.hr/tvrtka/aviana-promet-doo/MMIB25xD',
        // 'https://www.companywall.hr/tvrtka/ksenija-palic-usluge-jdoo/MMIB29tY',
        // 'https://www.companywall.hr/tvrtka/mali-ducan-jdoo---u-stecaju/MMIB2HnR',
        // 'https://www.companywall.hr/tvrtka/gibor-jdoo/MMIB2ODC',
        // 'https://www.companywall.hr/tvrtka/imperial-porec-jdoo-u-stecaju/MMIB2Tb0',
        // 'https://www.companywall.hr/tvrtka/galaxy-jdoo/MMIB2X4q',
        // 'https://www.companywall.hr/tvrtka/zdravstvena-skrb-nedic/MMIB2bOD',
        // 'https://www.companywall.hr/tvrtka/lotus-jdoo/MMIB2fFY',
        // 'https://www.companywall.hr/tvrtka/capljina-jdoo-u-stecaju/MMIB2j5R',
        // 'https://www.companywall.hr/tvrtka/4play-jdoo/MMIB2nwC',
        // 'https://www.companywall.hr/tvrtka/hekla-projekt-doo/MMxUun20',
        // 'https://www.companywall.hr/tvrtka/enesta-jdoo-u-stecaju/MMIB2sq0',
        // 'https://www.companywall.hr/tvrtka/lipa-doo/MMIB2wiq',
        // 'https://www.companywall.hr/tvrtka/auto-extreme-jdoo-u-stecaju/MMIBO1dD',
        // 'https://www.companywall.hr/tvrtka/svi-van-jdoo/MMIBOAXY',
        // 'https://www.companywall.hr/tvrtka/prisadi-jdoo/MMIBOG6R',
        // 'https://www.companywall.hr/tvrtka/professional-football-network-doo/MMIBO2IC',
        // 'https://www.companywall.hr/tvrtka/ss-jdoo/MMIBOSA0',
        // 'https://www.companywall.hr/tvrtka/elemental-studios-doo/MMIBOVzq',
        // 'https://www.companywall.hr/tvrtka/dobrila-instalacije-jdoo/MMIBOZsD',
        // 'https://www.companywall.hr/tvrtka/hart-group-d-o-o-u-stecaju/MMIBO8lY',
        // 'https://www.companywall.hr/tvrtka/leda-doo/MMxUusBq',
        // 'https://www.companywall.hr/tvrtka/own-solutions-d-o-o/MMIBOhfR',
        // 'https://www.companywall.hr/tvrtka/overseas-business-alliance-d-o-o-u-stecaju/MMIBONZC',
        // 'https://www.companywall.hr/tvrtka/panonia-sailing-d-o-o/MMIBOrU0',
        // 'https://www.companywall.hr/tvrtka/likvidacijska-masa-iza-van-der-spuy-doo-u-likvidaciji/MMIBOvLq',
        // 'https://www.companywall.hr/tvrtka/dinea--j-d-o-o/MMIBPxBD',
        // 'https://www.companywall.hr/tvrtka/eco-media-d-o-o/MMIBP71Y',
        // 'https://www.companywall.hr/tvrtka/idemo-dalje-jdoo/MMIBPCuR',
        // 'https://www.companywall.hr/tvrtka/tri-kolora-jdoo-u-stecaju/MMIBPKoC',
        // 'https://www.companywall.hr/tvrtka/siskov-jdoo/MMIBPRh0',
        // 'https://www.companywall.hr/tvrtka/elektro-vozila-doo/MMIBP4bq',
        // 'https://www.companywall.hr/tvrtka/bivelo-doo/MMxUuw1D',
        // 'https://www.companywall.hr/tvrtka/ri-plin-j-d-o-o/MMIBPYVD',
        // 'https://www.companywall.hr/tvrtka/hibbard-jdoo/MMIBPdPY',
        // 'https://www.companywall.hr/tvrtka/mobitel-trgovina-jdoo/MMIBPDGR',
        // 'https://www.companywall.hr/tvrtka/stellaria-doo/MMIBPl3C',
        // 'https://www.companywall.hr/tvrtka/parketi-life-jdoo/MMIBPpy0',
        // 'https://www.companywall.hr/tvrtka/moj-san-jdoo/MMIBPtqq',
        // 'https://www.companywall.hr/tvrtka/sport-nam-jdoo/MMIBPzjD',
        // 'https://www.companywall.hr/tvrtka/tehnika-i-montaza-jdoo/MMIBR58Y',
        // 'https://www.companywall.hr/tvrtka/connect-service-jdoo/MMIBRBJR',
        // 'https://www.companywall.hr/tvrtka/slatina-jdoo/MMIBRISC',
        // 'https://www.companywall.hr/tvrtka/ri-pos-d-o-o/MMxUvxuY',
        // 'https://www.companywall.hr/tvrtka/kosinac-doo/MMIBRPK0',
        // 'https://www.companywall.hr/tvrtka/bude-doo/MMIBRUAq',
        // 'https://www.companywall.hr/tvrtka/incentive-trade--doo/MMIBRJ0D',
        // 'https://www.companywall.hr/tvrtka/silhouette-doo/MMIBRbQY',
        // 'https://www.companywall.hr/tvrtka/franic-poslovno-savjetovanje-jdoo/MMIBRfNR',
        // 'https://www.companywall.hr/tvrtka/uciliste-era/MMIBRjgC',
        // 'https://www.companywall.hr/tvrtka/fam-immo-doo/MMIBRoa0',
        // 'https://www.companywall.hr/tvrtka/accountable-doo/MMIBRQUq',
        // 'https://www.companywall.hr/tvrtka/365-coffee-doo/MMIBRy2D',
        // 'https://www.companywall.hr/tvrtka/schusterwood-doo/MMIB6ECY',
        // 'https://www.companywall.hr/tvrtka/ecalis-doo/MM9J8Dq',
        // 'https://www.companywall.hr/tvrtka/crnac-d-o-o/MMxUv7oR',
        // 'https://www.companywall.hr/tvrtka/wolfisport-jdoo/MMIB69ER',
        // 'https://www.companywall.hr/tvrtka/queen-night-jdoo-u-stecaju/MMIB6GvC',
        // 'https://www.companywall.hr/tvrtka/lana-zdesic-jdoo/MMIB62p0',
        // 'https://www.companywall.hr/tvrtka/porat-graditeljstvo-doo/MMIB6Shq',
        // 'https://www.companywall.hr/tvrtka/matejak-krama-trgovina-jdoo/MMIB6WcD',
        // 'https://www.companywall.hr/tvrtka/ram-solucije-jdoo/MMIB6aWY',
        // 'https://www.companywall.hr/tvrtka/maja-bilicic-jdoo/MMIB6eRR',
        // 'https://www.companywall.hr/tvrtka/avens-doo/MMIB6iHC',
        // 'https://www.companywall.hr/tvrtka/auto-brunevi-doo/MMIB6n70',
        // 'https://www.companywall.hr/tvrtka/neque-error-doo/MMIB6ryq',
        // 'https://www.companywall.hr/tvrtka/silvek-tim-jednostavno-drustvo-s-ogranicenom-odgovornoscu-za-graditeljstvo-proizvodnju-i-usluge-u-st/MMxUvFhC',
        // 'https://www.companywall.hr/tvrtka/adduco-expert-doo/MMIB6vrD',
        // 'https://www.companywall.hr/tvrtka/sotir-trade-jdoo/MMIBSxkY',
        // 'https://www.companywall.hr/tvrtka/architechs-hosting-doo/MMIBS7eR',
        // 'https://www.companywall.hr/tvrtka/virtual-card-services-jdoo-u-stecaju/MMIBSFYC',
        // 'https://www.companywall.hr/tvrtka/eding-telecom-doo/MMIBSLT0',
        // 'https://www.companywall.hr/tvrtka/miro-balis-jdoo/MMIBS6Kq',
        // 'https://www.companywall.hr/tvrtka/aditus-modni-nakit-jdoo/MMIBSV9D',
        // 'https://www.companywall.hr/tvrtka/patla-jdoo-u-likvidaciji/MMIBSZxY',
        // 'https://www.companywall.hr/tvrtka/marcella-jdoo/MMIBSdtR',
        // 'https://www.companywall.hr/tvrtka/luste-transport-prevozne-storitve-doo/MMIBSDnC',
        // 'https://www.companywall.hr/tvrtka/slatko-i-gorko-d-o-o/MMxUvLc0',
        // 'https://www.companywall.hr/tvrtka/stokic-jdoo/MMIBSqaq',
        // 'https://www.companywall.hr/tvrtka/dot-jdoo/MMIBSu4D',
        // 'https://www.companywall.hr/tvrtka/ledina-plus-doo/MMIBT0OY',
        // 'https://www.companywall.hr/tvrtka/scenario-jdoo/MMIBT3FR',
        // 'https://www.companywall.hr/tvrtka/delta-bau-doo/MMIBTC5C',
        // 'https://www.companywall.hr/tvrtka/valbandon-jdoo-u-stecaju/MMIBTIw0',
        // 'https://www.companywall.hr/tvrtka/bartulovic-jdoo/MMIBTPpq',
        // 'https://www.companywall.hr/tvrtka/cool-jdoo-u-stecaju/MMIBTUiD',
        // 'https://www.companywall.hr/tvrtka/pfu-ecology-advisor-jdoo/MMIBTJdY',
        // 'https://www.companywall.hr/tvrtka/explico-doo/MMxUv6Vq',
        // 'https://www.companywall.hr/tvrtka/upf-consulenza-internazionale-jdoo/MMIBTcXR',
        // 'https://www.companywall.hr/tvrtka/energia-e-consulenza-jdoo/MMIBTg6C',
        // 'https://www.companywall.hr/tvrtka/ujedinjeni-nakladnici-jdoo/MMIBTkI0',
        // 'https://www.companywall.hr/tvrtka/zone-group-d-o-o/MMIBTp7q',
        // 'https://www.companywall.hr/tvrtka/razvojna-agencija---odraz/MMIBTQzD',
        // 'https://www.companywall.hr/tvrtka/botanical-jdoo/MMIBTysY',
        // 'https://www.companywall.hr/tvrtka/zeljana-jdoo/MMIBUElR',
        // 'https://www.companywall.hr/tvrtka/hida-gradnja-doo/MMIBU9fC',
        // 'https://www.companywall.hr/tvrtka/pivot-doo/MMIBUHZ0',
        // 'https://www.companywall.hr/tvrtka/doroci-jdoo-u-stecaju/MMIBUOTq',
        // 'https://www.companywall.hr/tvrtka/bok--j-d-o-o-u-stecaju/MMxUvVPD',
        // 'https://www.companywall.hr/tvrtka/why-beef-doo/MMIBUTLD',
        // 'https://www.companywall.hr/tvrtka/moonstone-production--doo/MMIBUXBY',
        // 'https://www.companywall.hr/tvrtka/aleks-taktika-jdoo/MMIBUb1R',
        // 'https://www.companywall.hr/tvrtka/aliquanta-doo/MMIBUeuC',
        // 'https://www.companywall.hr/tvrtka/dcmc-investimento-e-progettazione-jdoo/MMIBUio0',
        // 'https://www.companywall.hr/tvrtka/bp-recruitment--outsourcing-jdoo/MMIBUnDq',
        // 'https://www.companywall.hr/tvrtka/inova-tech-jdoo/MMIBUsbD',
        // 'https://www.companywall.hr/tvrtka/dom-majke-tereze-gudlin/MMIBUwVY',
        // 'https://www.companywall.hr/tvrtka/td-fit-jdoo/MMIB41PR',
        // 'https://www.companywall.hr/tvrtka/sanjek-transporti-jdoo/MMIB4AGC',
        // 'https://www.companywall.hr/tvrtka/rastovcanka-doo/MMxUvZGY',
        // 'https://www.companywall.hr/tvrtka/pajani-jdoo/MMIB4G30',
        // 'https://www.companywall.hr/tvrtka/lm---dent-doo/MMIB4Lwq',
        // 'https://www.companywall.hr/tvrtka/viro-plus-digital-doo/MMIB46qD',
        // 'https://www.companywall.hr/tvrtka/grafotehna-proizvodnja-komercijalne-ambalaze-doo-u-stecaju/MMIB4VjY',
        // 'https://www.companywall.hr/tvrtka/saskia-jdoo/MMIB4Z8R',
        // 'https://www.companywall.hr/tvrtka/smart-future-jdoo/MMIB48JC',
        // 'https://www.companywall.hr/tvrtka/aponia-adria--doo/MMIB4hS0',
        // 'https://www.companywall.hr/tvrtka/i4-invention-adria-doo/MMIB4NIq',
        // 'https://www.companywall.hr/tvrtka/smart-industry-jdoo/MMIB4rAD',
        // 'https://www.companywall.hr/tvrtka/flipendo-development-doo/MMIB4v0Y',
        // 'https://www.companywall.hr/tvrtka/izo-lim-dim-jdoo/MMxUv83R',
        // 'https://www.companywall.hr/tvrtka/ki-mel-doo/MMIBV0QR',
        // 'https://www.companywall.hr/tvrtka/dovono-projekti-doo/MMIBV3NC',
        // 'https://www.companywall.hr/tvrtka/rainbow-playground-jdoo-u-stecaju/MMIBVCg0',
        // 'https://www.companywall.hr/tvrtka/kaghen-design-jdoo/MMIBVKZq',
        // 'https://www.companywall.hr/tvrtka/mirko-borjan-promet-jdoo-u-stecaju/MMIBVRUD',
        // 'https://www.companywall.hr/tvrtka/gradzilla-doo/MMIBV42Y',
        // 'https://www.companywall.hr/tvrtka/novel-doo/MMIBVYCR',
        // 'https://www.companywall.hr/tvrtka/rule-gradnja-doo/MMIBVdEC',
        // 'https://www.companywall.hr/tvrtka/base-connection-doo/MMIBVgv0',
        // 'https://www.companywall.hr/tvrtka/farah-catering-jdoo-u-stecaju/MMIBVkoq',
        // 'https://www.companywall.hr/tvrtka/cakula-1-jdoo/MMxUvDyC',
        // 'https://www.companywall.hr/tvrtka/bella-faktor-doo/MMIBVphD',
        // 'https://www.companywall.hr/tvrtka/barakuda-consulting-jdoo/MMIBVtcY',
        // 'https://www.companywall.hr/tvrtka/auto-moto-alarm-jdoo-u-stecaju/MMIBVzWR',
        // 'https://www.companywall.hr/tvrtka/odvjetnicko-drustvo-cavic--partneri-doo/MMIBW5RC',
        // 'https://www.companywall.hr/tvrtka/kardum-graditeljstvo-doo/MMIBWBH0',
        // 'https://www.companywall.hr/tvrtka/c-design-doo/MMIBWI3q',
        // 'https://www.companywall.hr/tvrtka/healing-bit-doo/MMIBWOyD',
        // 'https://www.companywall.hr/tvrtka/si-camp-holiday-doo-u-stecaju/MMIBWTrY',
        // 'https://www.companywall.hr/tvrtka/lkw-knezevic-doo/MMIBWXkR',
        // 'https://www.companywall.hr/tvrtka/agro-hahne-dolle-doo/MMIBWbeC',
        // 'https://www.companywall.hr/tvrtka/euro---s-a-j-m--d-o-o/MMxUvlr0',
        // 'https://www.companywall.hr/tvrtka/felarona-doo-u-likvidaciji/MMIBWfY0',
        // 'https://www.companywall.hr/tvrtka/netoptik-doo/MMIBWjSq',
        // 'https://www.companywall.hr/tvrtka/sopa-trading-d-o-o/MMIBWoKD',
        // 'https://www.companywall.hr/tvrtka/lab-doo/MMIBWQ9Y',
        // 'https://www.companywall.hr/tvrtka/brightdock-d-o-o/MMIBWyxR',
        // 'https://www.companywall.hr/tvrtka/doris--lucija--doo/MMIBX1tC',
        // 'https://www.companywall.hr/tvrtka/petrusimul-doo/MMIBXAn0',
        // 'https://www.companywall.hr/tvrtka/ri-monting-d-o-o/MMIBXGgq',
        // 'https://www.companywall.hr/tvrtka/orthotec-doo/MMIBX2aD',
        // 'https://www.companywall.hr/tvrtka/seadro-doo/MMIBXS4Y',
        // 'https://www.companywall.hr/tvrtka/turbo-team-doo-u-likvidaciji/MMxUvqjq',
        // 'https://www.companywall.hr/tvrtka/zd-cargo-prijevoz-doo/MMIBXWOR',
        // 'https://www.companywall.hr/tvrtka/carpe-sol-agency-doo/MMIBXaFC',
        // 'https://www.companywall.hr/tvrtka/mmi-standard-doo/MMIBXe50',
        // 'https://www.companywall.hr/tvrtka/prime-doo/MMIBXhvq',
        // 'https://www.companywall.hr/tvrtka/simmon-jahta-doo/MMIBXNpD',
        // 'https://www.companywall.hr/tvrtka/miskovic--miskovic-odvjetnicko-drustvo-doo/MMIBXriY',
        // 'https://www.companywall.hr/tvrtka/hn-eco-doo/MMIBXvdR',
        // 'https://www.companywall.hr/tvrtka/matstar-doo/MMIBJxXC',
        // 'https://www.companywall.hr/tvrtka/smb-srebrnjak-doo/MMIBJ760',
        // 'https://www.companywall.hr/tvrtka/daibau-doo/MMIBJFHq',
        // 'https://www.companywall.hr/tvrtka/bio-sativa-doo/MM9JhbD',
        // 'https://www.companywall.hr/tvrtka/cicak-savjetovanje-doo/MMxUvu8D',
        // 'https://www.companywall.hr/tvrtka/poslovna-sigurnost-doo/MMIBJL7D',
        // 'https://www.companywall.hr/tvrtka/black-sheep-doo/MMIBJRzY',
        // 'https://www.companywall.hr/tvrtka/sweet-cakes-jdoo/MMIBJ4sR',
        // 'https://www.companywall.hr/tvrtka/sizif-jdoo-u-likvidaciji/MMIBJYlC',
        // 'https://www.companywall.hr/tvrtka/asm-unlimited-d-o-o/MMIBJdf0',
        // 'https://www.companywall.hr/tvrtka/vjetroelektrana-rust-doo/MMIBJDYq',
        // 'https://www.companywall.hr/tvrtka/ziro-design-jdoo-u-stecaju/MMIBJlTD',
        // 'https://www.companywall.hr/tvrtka/lumenos-jdoo/MMIBJqLY',
        // 'https://www.companywall.hr/tvrtka/iternal-jdoo/MMIBJuBR',
        // 'https://www.companywall.hr/tvrtka/the-cheapest-jdoo/MMIBY01C',
        // 'https://www.companywall.hr/tvrtka/miro-tim-doo/MMxUw0JY',
        // 'https://www.companywall.hr/tvrtka/erosi-d-o-o/MMIBY5u0',
        // 'https://www.companywall.hr/tvrtka/parra-torres-jdoo/MMIBYBnq',
        // 'https://www.companywall.hr/tvrtka/afrooza-ice-jdoo/MMIBYIDD',
        // 'https://www.companywall.hr/tvrtka/novembre-11-jdoo/MMIBYPbY',
        // 'https://www.companywall.hr/tvrtka/dreieck-jdoo/MMIBYUVR',
        // 'https://www.companywall.hr/tvrtka/brami-knjigovodstvo-jdoo/MMIBYJPC',
        // 'https://www.companywall.hr/tvrtka/majta-spreha-jdoo/MMIBYcG0',
        // 'https://www.companywall.hr/tvrtka/veseljko-jdoo/MMIBYg5q',
        // 'https://www.companywall.hr/tvrtka/sljedeci-korak-jdoo/MMIBYjwD',
        // 'https://www.companywall.hr/tvrtka/vatreniturudic-jdoo-u-stecaju/MMIBYoqY',
        // 'https://www.companywall.hr/tvrtka/eron-promet-doo/MMxUw3SR',
        // 'https://www.companywall.hr/tvrtka/kartpak-ambalaza-doo/MMIBYQjR',
        // 'https://www.companywall.hr/tvrtka/clean-corner-jdoo/MMIBYy8C',
        // 'https://www.companywall.hr/tvrtka/pnd-strategija-doo/MMIBZEJ0',
        // 'https://www.companywall.hr/tvrtka/trempetic-jdoo/MMIBZ96q',
        // 'https://www.companywall.hr/tvrtka/getnet-jdoo/MMIBZHID',
        // 'https://www.companywall.hr/tvrtka/fides-spes-jdoo/MMIBZOAY',
        // 'https://www.companywall.hr/tvrtka/matea-turcin-jdoo/MMIBZT0R',
        // 'https://www.companywall.hr/tvrtka/kompa-promet-doo/MMIBZWQC',
        // 'https://www.companywall.hr/tvrtka/dictator-doo/MMIBZaN0',
        // 'https://www.companywall.hr/tvrtka/antonio-semren-jdoo/MMIBZefq',
        // 'https://www.companywall.hr/tvrtka/junior-doo/MMxUwCKC',
        // 'https://www.companywall.hr/tvrtka/beauty-project-jdoo/MMIBZiZD',
        // // 'https://www.companywall.hr/tvrtka/lumar-2007-jdoo/MMIBZnUY',
        // 'https://www.companywall.hr/tvrtka/matas-automatika-jdoo/MMIBZs2R',
        // 'https://www.companywall.hr/tvrtka/manac-technology-doo-u-stecaju/MMIBZwCC',
        // 'https://www.companywall.hr/tvrtka/instalacije-senjak-jdoo/MMIBa1E0',
        // 'https://www.companywall.hr/tvrtka/red-fox-jdoo/MMIBa7uq',
        // 'https://www.companywall.hr/tvrtka/vranjes-graditeljstvo-jdoo/MMIBaFoD',
        // 'https://www.companywall.hr/tvrtka/sima-consulting-jdoo/MMIBaLhY',
        // 'https://www.companywall.hr/tvrtka/air-cooling-doo/MMIBa6cR',
        // 'https://www.companywall.hr/tvrtka/gamabon-doo/MMxUwK90',
        // 'https://www.companywall.hr/tvrtka/weld-mag-doo/MMIBaqrR',
        // 'https://www.companywall.hr/tvrtka/cityjumper-jdoo/MMIBaukC',
        // 'https://www.companywall.hr/tvrtka/terapijski-centar-jdoo/MMIBb0e0',
        // 'https://www.companywall.hr/tvrtka/autopromet-ciko-doo/MMIBb3Jq',
        // 'https://www.companywall.hr/tvrtka/la-mirada-osijek-jdoo/MMIBbCSD',
        // 'https://www.companywall.hr/tvrtka/d--r-finance-group-jdoo-u-stecaju/MMIBbKKY',
        // 'https://www.companywall.hr/tvrtka/kings-caffe-d-o-o/MMxUwR0q',
        // 'https://www.companywall.hr/tvrtka/breath--massage-doo/MMIBbR9R',
        // 'https://www.companywall.hr/tvrtka/kocka-limarija-jdoo/MMIBb4xC',
        // 'https://www.companywall.hr/tvrtka/acp-doo/MMIBbJt0',
        // 'https://www.companywall.hr/tvrtka/in-clouds-doo/MMIBbcNq',
        // 'https://www.companywall.hr/tvrtka/sara-ribolov-jdoo/MMIBbkaY',
        // 'https://www.companywall.hr/tvrtka/novotehna-upravljanje-d-o-o/MMIBbp4R',
        // 'https://www.companywall.hr/tvrtka/dalis-j-d-o-o/MMIBbtOC',
        // 'https://www.companywall.hr/tvrtka/pakovina-jdoo/MMIBbzF0',
        // 'https://www.companywall.hr/tvrtka/infinite-k-digital-studios-d-o-o/MMIBc5Eq',
        // 'https://www.companywall.hr/tvrtka/franc-mont-doo/MMxUwUQD',
        // 'https://www.companywall.hr/tvrtka/k-bau-d-o-o/MMIBc9vD',
        // 'https://www.companywall.hr/tvrtka/brunave-doo/MMIBcHpY',
        // 'https://www.companywall.hr/tvrtka/kurenat-jdoo/MMIBcOiR',
        // 'https://www.companywall.hr/tvrtka/hiller--doo-u-stecaju/MMIBcTdC',
        // 'https://www.companywall.hr/tvrtka/porto-sole-d-o-o/MMIBcXX0',
        // 'https://www.companywall.hr/tvrtka/gavran-jdoo/MMIBcbRq',
        // 'https://www.companywall.hr/tvrtka/kru-al-gradnja-jdoo/MMIBcfHD',
        // 'https://www.companywall.hr/tvrtka/likos-nekretnine-doo/MMIBcj7Y',
        // 'https://www.companywall.hr/tvrtka/interijeri-pulek-jdoo/MMIBcnzR',
        // 'https://www.companywall.hr/tvrtka/new-territory-jdoo/MMIBcssC',
        // 'https://www.companywall.hr/tvrtka/im-drustvo-doo-u-stecaju/MMxUwJNY',
        // 'https://www.companywall.hr/tvrtka/double-lens-solutions-doo/MMIBcwl0',
        // 'https://www.companywall.hr/tvrtka/pajko-savjetovanje-jdoo-u-likvidaciji/MMIBd1eq',
        // 'https://www.companywall.hr/tvrtka/kobama-pro-doo/MMIBdAYD',
        // 'https://www.companywall.hr/tvrtka/rental-solutions-doo/MMIBdGTY',
        // 'https://www.companywall.hr/tvrtka/web-kreator-jdoo-u-stecaju/MMIBd2LR',
        // 'https://www.companywall.hr/tvrtka/zdravlje-za-sve-jdoo/MMIBdSBC',
        // 'https://www.companywall.hr/tvrtka/elektro-vod-doo/MMIBdW10',
        // 'https://www.companywall.hr/tvrtka/genetski-kod-jdoo/MMIBdZtq',
        // 'https://www.companywall.hr/tvrtka/cumastil-doo/MMIBd8nD',
        // 'https://www.companywall.hr/tvrtka/tanod-gradnja-doo/MMIBdhDY',
        // 'https://www.companywall.hr/tvrtka/promo-aurum-doo/MMxUwcgR',
        // 'https://www.companywall.hr/tvrtka/lipic-nek-doo/MMIBdNbR',
        // 'https://www.companywall.hr/tvrtka/logic2data-doo/MMIBdrVC',
        // 'https://www.companywall.hr/tvrtka/bogdan-promet-doo-u-likvidaciji/MMIBdvP0',
        // 'https://www.companywall.hr/tvrtka/trifora-ing-doo/MMIB8xFq',
        // 'https://www.companywall.hr/tvrtka/osovik-promet-doo/MMIB875D',
        // 'https://www.companywall.hr/tvrtka/fiasco-blue-jdoo-u-stecaju/MMIB8CwY',
        // 'https://www.companywall.hr/tvrtka/francisco-jdoo-u-stecaju/MMIB8KqR',
        // 'https://www.companywall.hr/tvrtka/universo-jdoo-u-stecaju/MMIB8RjC',
        // 'https://www.companywall.hr/tvrtka/jerome-rovera-doo/MMIB8480',
        // 'https://www.companywall.hr/tvrtka/lesnika-energy-doo/MMIB8YXq',
        // 'https://www.companywall.hr/tvrtka/instal-montaza-doo/MMxUwgaC',
        // 'https://www.companywall.hr/tvrtka/tmt-bau-doo/MMIBe5fD',
        // 'https://www.companywall.hr/tvrtka/laurent-cuille-jdoo/MMIBeBZY',
        // 'https://www.companywall.hr/tvrtka/djecji-vrtic-gardelin/MMIBeIUR',
        // 'https://www.companywall.hr/tvrtka/iph/MMIBeP2C',
        // 'https://www.companywall.hr/tvrtka/fkt-doo-u-stecaju/MM9JNVY',
        // 'https://www.companywall.hr/tvrtka/via-magriz-jdoo-u-stecaju/MMxUwk40',
        // 'https://www.companywall.hr/tvrtka/osnovna-skola-jesenice-dugi-rat/MMIBeJ1q',
        // 'https://www.companywall.hr/tvrtka/centar-za-odgoj-i-obrazovanje-goljak/MMIBebuD',
        // 'https://www.companywall.hr/tvrtka/antik-dakovo-jdoo-u-stecaju/MMIBefoY',
        // 'https://www.companywall.hr/tvrtka/crveno-more-jdoo/MMIBejhR',
        // 'https://www.companywall.hr/tvrtka/slice-of-life-films-production-doo/MMIBeocC',
        // 'https://www.companywall.hr/tvrtka/bar-laguna-jdoo-u-stecaju/MMIBeQW0',
        // 'https://www.companywall.hr/tvrtka/pvi-project-3-doo/MMIBeyPq',
        // 'https://www.companywall.hr/tvrtka/spencer-butler-jdoo/MMIBfEGD',
        // 'https://www.companywall.hr/tvrtka/verbis-j-d-o-o/MMIBf93Y',
        // 'https://www.companywall.hr/tvrtka/casino-kristal-umag-d-o-o-u-stecaju/MMxUwp2q',
        // 'https://www.companywall.hr/tvrtka/speed-clean-j-d-o-o/MMIBfGyR',
        // 'https://www.companywall.hr/tvrtka/auto-loncar--speed-assistance-d-o-o/MMIBf2rC',
        // 'https://www.companywall.hr/tvrtka/svijet-stolica-doo/MMIBfSk0',
        // 'https://www.companywall.hr/tvrtka/madunic-projektiranje-i-gradenje-jdoo/MMIBfW8q',
        // 'https://www.companywall.hr/tvrtka/bukal-jdoo/MMIBfaJD',
        // 'https://www.companywall.hr/tvrtka/lina-leo-jdoo-u-stecaju/MMIBfeSY',
        // 'https://www.companywall.hr/tvrtka/pro-weld-jdoo/MMIBfiKR',
        // 'https://www.companywall.hr/tvrtka/jure--roko-doo/MMIBfn9C',
        // 'https://www.companywall.hr/tvrtka/novi-consulting-doo/MMIBfsx0',
        // 'https://www.companywall.hr/tvrtka/domek-hrana-jdoo-u-stecaju/MMIBfvQq',
        // 'https://www.companywall.hr/tvrtka/lerga-dom--jdoo/MMxUwtCD',
        // 'https://www.companywall.hr/tvrtka/maslinovica-doo/MMIBgxND',
        // 'https://www.companywall.hr/tvrtka/la-perla-charter-doo/MMIBg7gY',
        // 'https://www.companywall.hr/tvrtka/ustanova-za-obrazovanje-odraslih-inspekt/MMIBgFaR',
        // 'https://www.companywall.hr/tvrtka/cars-for-you-doo/MMIBgL4C',
        // 'https://www.companywall.hr/tvrtka/energosigurnost-jdoo/MMIBg6O0',
        // 'https://www.companywall.hr/tvrtka/mlin-pukanic-doo/MMIBgVCq',
        // 'https://www.companywall.hr/tvrtka/statika-projekt-doo/MMIBgZED',
        // 'https://www.companywall.hr/tvrtka/uvi-shop-doo/MMIBgdvY',
        // 'https://www.companywall.hr/tvrtka/zgi-doo/MMIBgDpR',
        // 'https://www.companywall.hr/tvrtka/smart-cadres-doo/MMIBgliC',
        // 'https://www.companywall.hr/tvrtka/park-pub--d-o-o/MMxUwzEY',
        // 'https://www.companywall.hr/tvrtka/roorelax-jdoo/MMIBgqd0',
        // 'https://www.companywall.hr/tvrtka/izradi-website-jdoo/MMIBguWq',
        // 'https://www.companywall.hr/tvrtka/jedan-bit-doo/MMIBD0RD',
        // 'https://www.companywall.hr/tvrtka/interijeri-ibvt-doo/MMIBD3HY',
        // 'https://www.companywall.hr/tvrtka/stozina-2018-jdoo/MMIBDC7R',
        // 'https://www.companywall.hr/tvrtka/corpus-dip-doo/MMIBDIzC',
        // 'https://www.companywall.hr/tvrtka/carski-dojam-jdoo/MMIBDPs0',
        // 'https://www.companywall.hr/tvrtka/strukelj-truck-services-jdoo/MMIBDUkq',
        // 'https://www.companywall.hr/tvrtka/color-rad-jdoo/MMIBDJeD',
        // 'https://www.companywall.hr/tvrtka/zugaj-cafe-jdoo-u-stecaju/MMIBDcYY',
        // 'https://www.companywall.hr/tvrtka/renger-d-o-o/MMxUyEvR',
        // 'https://www.companywall.hr/tvrtka/filion-green-doo/MMIBDgTR',
        // 'https://www.companywall.hr/tvrtka/ad-sistemi-jdoo/MMIBDkLC',
        // 'https://www.companywall.hr/tvrtka/zagorje-drvo-jdoo-u-stecaju/MMIBDpB0',
        // 'https://www.companywall.hr/tvrtka/fama-volat-ugostiteljstvo-jdoo-u-stecaju/MMIBDtxq',
        // 'https://www.companywall.hr/tvrtka/exodium-trgovina-jdoo/MMIBDytD',
        // 'https://www.companywall.hr/tvrtka/mezei-veletrgovina-jdoo-u-stecaju/MMIBhEnY',
        // 'https://www.companywall.hr/tvrtka/zen-spa-doo/MMIBh9DR',
        // 'https://www.companywall.hr/tvrtka/centar-za-pomoc-i-njegu-mario-u-likvidaciji/MMIBhHbC',
        // 'https://www.companywall.hr/tvrtka/centar-za-pomoc-i-njegu-rupcic/MMIBhOV0',
        // 'https://www.companywall.hr/tvrtka/ustanova-za-zdravstvenu-njegu-i-rehabilitaciju-u-kuci-vitalis-medica/MMIBhTOq',
        // 'https://www.companywall.hr/tvrtka/tergus-liber-inscriptus-doo/MMxUy9pC',
        // 'https://www.companywall.hr/tvrtka/svitava-jdoo/MMIBhXFD',
        // 'https://www.companywall.hr/tvrtka/hd-code-doo/MMIBhb5Y',
        // 'https://www.companywall.hr/tvrtka/ms-shop-jdoo/MMIBhewR',
        // 'https://www.companywall.hr/tvrtka/sabrina-doo/MMIBhiqC',
        // 'https://www.companywall.hr/tvrtka/nit-nova-jdoo/MMIBhnj0',
        // 'https://www.companywall.hr/tvrtka/lija-jdoo/MMIBhsdq',
        // 'https://www.companywall.hr/tvrtka/subergradnja-jdoo/MMIBhwXD',
        // 'https://www.companywall.hr/tvrtka/capital-assembly-jdoo/MMIBi16Y',
        // 'https://www.companywall.hr/tvrtka/nutrition-shop-jdoo/MMIBiAIR',
        // 'https://www.companywall.hr/tvrtka/fliesen-gradnja-jdoo/MMIBiGAC',
        // 'https://www.companywall.hr/tvrtka/agro-simpa-doo/MMxUyHi0',
        // 'https://www.companywall.hr/tvrtka/orqa-doo/MMIBi200',
        // 'https://www.companywall.hr/tvrtka/hrnic-jdoo-u-stecaju/MMIBi6sq',
        // 'https://www.companywall.hr/tvrtka/dino-gradnja-jdoo-u-stecaju/MMIBiVlD',
        // 'https://www.companywall.hr/tvrtka/bella-napoli-jdoo/MMIBiZfY',
        // 'https://www.companywall.hr/tvrtka/tola-gradnja-doo/MMIBi8ZR',
        // 'https://www.companywall.hr/tvrtka/portieri-doo/MMIBihUC',
        // 'https://www.companywall.hr/tvrtka/umag-service-doo/MMIBiN20',
        // 'https://www.companywall.hr/tvrtka/sare-sol-doo/MMIBirBq',
        // 'https://www.companywall.hr/tvrtka/axco-solutions-d-o-o/MMIBiv1D',
        // 'https://www.companywall.hr/tvrtka/blocks-bricks--bits-d-o-o/MMIBj0uY',
        // 'https://www.companywall.hr/tvrtka/spes-plus-doo/MMxUyOcq',
        // 'https://www.companywall.hr/tvrtka/back-to-black-jdoo/MMIBj3oR',
        // 'https://www.companywall.hr/tvrtka/terra-et-anima-doo/MMIBjChC',
        // 'https://www.companywall.hr/tvrtka/plavi-gat-doo/MMIBjKc0',
        // 'https://www.companywall.hr/tvrtka/pajola-doo/MMIBjRVq',
        // 'https://www.companywall.hr/tvrtka/red-land-doo/MMIBj4PD',
        // 'https://www.companywall.hr/tvrtka/stem-promet-jdoo/MMIBjYGY',
        // 'https://www.companywall.hr/tvrtka/pemo-centar-zagreb-doo/MMIBjd3R',
        // 'https://www.companywall.hr/tvrtka/ic-tours-doo/MMIBjgyC',
        // 'https://www.companywall.hr/tvrtka/salon-ljepote-freya-jdoo/MMIBjkr0',
        // 'https://www.companywall.hr/tvrtka/next-trans-jdoo/MMIBjpjq',
        // 'https://www.companywall.hr/tvrtka/eskadrila-doo/MMxUyTWD',
        // 'https://www.companywall.hr/tvrtka/hapo-doo/MMIBjt8D',
        // 'https://www.companywall.hr/tvrtka/street-trans-jdoo/MMIBjzJY',
        // 'https://www.companywall.hr/tvrtka/mauris-jdoo/MMIBk5SR',
        // 'https://www.companywall.hr/tvrtka/pro-step-doo/MMIBkBKC',
        // 'https://www.companywall.hr/tvrtka/grade-promet-doo-u-stecaju/MMIBkI90',
        // 'https://www.companywall.hr/tvrtka/braca-peric-pekare-jdoo/MMIBkP0q',
        // 'https://www.companywall.hr/tvrtka/palidis-doo/MMIBkTQD',
        // 'https://www.companywall.hr/tvrtka/tsf-termo-doo/MMIBkXNY',
        // 'https://www.companywall.hr/tvrtka/helena-kunkic-jdoo/MMIBkbgR',
        // 'https://www.companywall.hr/tvrtka/marina-pizza-jdoo/MMIBkfaC',
        // 'https://www.companywall.hr/tvrtka/novi-stil-jdoo-u-stecaju/MMxUyXRY',
        // 'https://www.companywall.hr/tvrtka/start-level-jdoo/MMIBkj40',
        // 'https://www.companywall.hr/tvrtka/miador-doo/MMIBko2q',
        // 'https://www.companywall.hr/tvrtka/bacos-doo/MMIBkQCD',
        // 'https://www.companywall.hr/tvrtka/axis-partners-doo/MMIBkyEY',
        // 'https://www.companywall.hr/tvrtka/lumme-doo/MMIBl1vR',
        // 'https://www.companywall.hr/tvrtka/giacometti-doo/MMIBlApC',
        // 'https://www.companywall.hr/tvrtka/hybrid-shield-doo/MMIBlGi0',
        // 'https://www.companywall.hr/tvrtka/fisherija-doo/MMIBl2cq',
        // 'https://www.companywall.hr/tvrtka/silver-silvio-doo/MMIBlSWD',
        // 'https://www.companywall.hr/tvrtka/monita-sistem-jdoo/MMIBlWRY',
        // 'https://www.companywall.hr/tvrtka/emo-mancipo-doo/MM9JrPR',
        // 'https://www.companywall.hr/tvrtka/mont-inst-jdoo-u-likvidaciji/MMxUybHR',
        // 'https://www.companywall.hr/tvrtka/dado-fasade-jdoo/MMIBlaHR',
        // 'https://www.companywall.hr/tvrtka/radiant-quota-jdoo/MMIBle7C',
        // 'https://www.companywall.hr/tvrtka/ivan-berisic-jdoo/MMIBlhz0',
        // 'https://www.companywall.hr/tvrtka/mkd-sistem--jdoo-u-stecaju/MMIBlNrq',
        // 'https://www.companywall.hr/tvrtka/gorica-plast-doo/MMIBlrkD',
        // 'https://www.companywall.hr/tvrtka/europoint-doo/MMIBlveY',
        // 'https://www.companywall.hr/tvrtka/ugostiteljstvo-burdalic-jdoo/MMIBNxYR',
        // 'https://www.companywall.hr/tvrtka/kapljica-alexander-doo/MMIBN7TC',
        // 'https://www.companywall.hr/tvrtka/racunovodstvo-frarib-jdoo/MMIBNFL0',
        // 'https://www.companywall.hr/tvrtka/ria-natura-jdoo---u-stecaju/MMIBNL9q',
        // 'https://www.companywall.hr/tvrtka/kruh-i-vino-j-d-o-o-u-stecaju/MMxUyf7C',
        // 'https://www.companywall.hr/tvrtka/tko-te-sisa-jdoo/MMIBN6xD',
        // 'https://www.companywall.hr/tvrtka/luce-jdoo/MMIBN4tY',
        // 'https://www.companywall.hr/tvrtka/vukoil-doo/MMIBNYnR',
        // 'https://www.companywall.hr/tvrtka/aztek-tehnika-doo-u-stecaju/MMIBNdDC',
        // 'https://www.companywall.hr/tvrtka/dugi-put-jdoo-u-stecaju/MMIBNDb0',
        // 'https://www.companywall.hr/tvrtka/naser-gradnja-doo/MMIBNl4q',
        // 'https://www.companywall.hr/tvrtka/kirianova-doo/MMIBNqOD',
        // 'https://www.companywall.hr/tvrtka/k--k-living-doo/MMIBNuFY',
        // 'https://www.companywall.hr/tvrtka/nz-nekretnine-d-o-o/MMIBn05R',
        // 'https://www.companywall.hr/tvrtka/vidakovic-m-j-d-o-o-u-likvidaciji/MMIBn5wC',
        // 'https://www.companywall.hr/tvrtka/scateo-doo-u-stecaju/MMxUyiz0',
        // 'https://www.companywall.hr/tvrtka/m--m-hi-tech-j-d-o-o/MMIBnBq0',
        // 'https://www.companywall.hr/tvrtka/arora-d-o-o/MMIBnIiq',
        // 'https://www.companywall.hr/tvrtka/milardovic-j-d-o-o/MMIBnPdD',
        // 'https://www.companywall.hr/tvrtka/drvo-design-j-d-o-o/MMIBnUXY',
        // 'https://www.companywall.hr/tvrtka/nautic-support-doo/MMIBnJ6R',
        // 'https://www.companywall.hr/tvrtka/olive-gardens-jdoo/MMIBncIC',
        // 'https://www.companywall.hr/tvrtka/eurospin-hrvatska-d-o-o/MMIBngA0',
        // 'https://www.companywall.hr/tvrtka/rolica-2-jdoo/MMIBnjzq',
        // 'https://www.companywall.hr/tvrtka/construction-support-doo/MMIBnosD',
        // 'https://www.companywall.hr/tvrtka/livajic-gradnja-jdoo/MMIBnQlY',
        // 'https://www.companywall.hr/tvrtka/conto-id-jdoo/MMxUynrq',
        // 'https://www.companywall.hr/tvrtka/estetic-doo/MMIBnyfR',
        // 'https://www.companywall.hr/tvrtka/architekton-doo/MMIBoEZC',
        // 'https://www.companywall.hr/tvrtka/splitski-krov-jdoo-u-stecaju/MMIBo9U0',
        // 'https://www.companywall.hr/tvrtka/ap-taxi-jdoo-u-stecaju/MMIBoHLq',
        // 'https://www.companywall.hr/tvrtka/brac-city-heliport-jdoo/MMIBoOBD',
        // 'https://www.companywall.hr/tvrtka/little-cup-jdoo-u-stecaju/MMIBoT1Y',
        // 'https://www.companywall.hr/tvrtka/gpb-doo-citluk/MMIBoWuR',
        // 'https://www.companywall.hr/tvrtka/euro-san-jdoo/MMIBoeh0',
        // 'https://www.companywall.hr/tvrtka/merien-king-jdoo/MMIBoibq',
        // 'https://www.companywall.hr/tvrtka/veseli-turisti-doo-u-stecaju/MMxUyskD',
        // 'https://www.companywall.hr/tvrtka/synox-jdoo/MMIBonVD',
        // 'https://www.companywall.hr/tvrtka/oaza-jdoo-u-stecaju/MMIBosPY',
        // 'https://www.companywall.hr/tvrtka/mtg-vila-doo/MMIBowGR',
        // 'https://www.companywall.hr/tvrtka/kreativa-dizajn-jdoo/MMIBp13C',
        // 'https://www.companywall.hr/tvrtka/fil-cosic-jdoo/MMIBp7y0',
        // 'https://www.companywall.hr/tvrtka/dan-d-doo/MMIBpFqq',
        // 'https://www.companywall.hr/tvrtka/olive-real-estate-doo/MMIBpLjD',
        // 'https://www.companywall.hr/tvrtka/vulin-grupa-jdoo/MMIBp68Y',
        // 'https://www.companywall.hr/tvrtka/pseudorandom-doo/MMIBpVJR',
        // 'https://www.companywall.hr/tvrtka/tectum-doo/MMIBpZSC',
        // 'https://www.companywall.hr/tvrtka/coprintdoo/MMxUyweY',
        // 'https://www.companywall.hr/tvrtka/big-ben-doo/MMIBp8K0',
        // 'https://www.companywall.hr/tvrtka/schmidt-yachting-doo/MMIBphAq',
        // 'https://www.companywall.hr/tvrtka/mislav-markov-jdoo/MMIBpN0D',
        // 'https://www.companywall.hr/tvrtka/beletic-1985-jdoo/MMIBpqQY',
        // 'https://www.companywall.hr/tvrtka/spera-interijeri-jdoo/MMIBpuNR',
        // 'https://www.companywall.hr/tvrtka/belive-bell-doo/MMIBq0gC',
        // 'https://www.companywall.hr/tvrtka/jepakaj-doo/MMIBq3a0',
        // 'https://www.companywall.hr/tvrtka/kumovi-gradnja-jdoo/MMIBqCUq',
        // 'https://www.companywall.hr/tvrtka/fc-adria-solutions-doo/MMIBqK2D',
        // 'https://www.companywall.hr/tvrtka/kaiserlehner-immobilien-doo/MMIBqRCY',
        // 'https://www.companywall.hr/tvrtka/sial-d-o-o/MMxUz1YR',
        // 'https://www.companywall.hr/tvrtka/gamestore-jdoo/MMIBq4ER',
        // 'https://www.companywall.hr/tvrtka/magli-doo-u-stecaju/MMIBqJvC',
        // 'https://www.companywall.hr/tvrtka/goodhouse-jdoo/MMIBqcp0',
        // 'https://www.companywall.hr/tvrtka/your-way-jdoo/MMIBqghq',
        // 'https://www.companywall.hr/tvrtka/livadar-uredenje-jdoo/MMIBqkcD',
        // 'https://www.companywall.hr/tvrtka/ro-jo-sisak-usluge-jdoo-u-stecaju/MMIBqpWY',
        // 'https://www.companywall.hr/tvrtka/digitalna-slika-jdoo/MMIBqtRR',
        // 'https://www.companywall.hr/tvrtka/halimoski-jdoo/MMIBqzHC',
        // 'https://www.companywall.hr/tvrtka/sos-shop-jdoo/MMIBr570',
        // 'https://www.companywall.hr/tvrtka/stop-shop-doo/MMIBr9yq',
        // 'https://www.companywall.hr/tvrtka/vugica-amg-jdoo/MMxUzATC',
        // 'https://www.companywall.hr/tvrtka/pfeifer-graditeljstvo-jdoo/MMIBrHrD',
        // 'https://www.companywall.hr/tvrtka/mohan-tekstil-jdoo/MMIBrOkY',
        // 'https://www.companywall.hr/tvrtka/lutkarsko-uciliste-u-likvidaciji/MMIBrTeR',
        // 'https://www.companywall.hr/tvrtka/transphera-doo/MMIBrXYC',
        // 'https://www.companywall.hr/tvrtka/petropromotion-jdoo-u-stecaju/MMIBrbT0',
        // 'https://www.companywall.hr/tvrtka/zed-dizajn-jdoo/MMIBrfKq',
        // 'https://www.companywall.hr/tvrtka/europrima-savjetovanje-doo/MMIBrj9D',
        // 'https://www.companywall.hr/tvrtka/ga-me-caffe-jdoo/MMIBroxY',
        // 'https://www.companywall.hr/tvrtka/strelar-prom-jdoo/MMIBrstR',
        // 'https://www.companywall.hr/tvrtka/lalu-limo-service-doo/MMIBrwnC',
        // 'https://www.companywall.hr/tvrtka/eurogrupa-doo/MMxUzGL0',
        // 'https://www.companywall.hr/tvrtka/catino-projekt-doo/MMIBs1D0',
        // 'https://www.companywall.hr/tvrtka/tafel-usluge-jdoo/MMIBsAaq',
        // 'https://www.companywall.hr/tvrtka/humata-doo/MMIBsG4D',
        // 'https://www.companywall.hr/tvrtka/filip-petrovic-jdoo/MMIBs2OY',
        // 'https://www.companywall.hr/tvrtka/putem-oazae-doo/MMIBsSFR',
        // 'https://www.companywall.hr/tvrtka/salon-crnkovic-jdoo/MMIBsW5C',
        // 'https://www.companywall.hr/tvrtka/vugec---stocarstvo-jdoo/MMIBsZw0',
        // 'https://www.companywall.hr/tvrtka/topcic-skakalice-jdoo/MMIBs8pq',
        // 'https://www.companywall.hr/tvrtka/mobi-tehno-doo/MMxUz29q',
        // 'https://www.companywall.hr/tvrtka/lorenzia-jdoo-u-likvidaciji/MMIBsrXR',
        // 'https://www.companywall.hr/tvrtka/nemanja-kocic-jdoo/MMIBsv6C',
        // 'https://www.companywall.hr/tvrtka/plastika-kruger-j-d-o-o/MMIBQxI0',
        // 'https://www.companywall.hr/tvrtka/color-design-doo/MMIBQ77q',
        // 'https://www.companywall.hr/tvrtka/vutrans-doo/MMIBQCzD',
        // 'https://www.companywall.hr/tvrtka/consultatio-istra-doo/MMIBQKsY',
        // 'https://www.companywall.hr/tvrtka/velebit-group-d-o-o/MMIBQRlR',
        // 'https://www.companywall.hr/tvrtka/venandi-doo/MMIBQ4fC',
        // 'https://www.companywall.hr/tvrtka/eventfully-doo/MMIBQYZ0',
        // 'https://www.companywall.hr/tvrtka/addl-jolara-doo/MMIBQdTq',
        // 'https://www.companywall.hr/tvrtka/decentis-d-o-o/MM9JvGC',
        // 'https://www.companywall.hr/tvrtka/vet-life-doo/MMxUzSxD',
        // 'https://www.companywall.hr/tvrtka/lumbui-doo/MMIBQDLD',
        // 'https://www.companywall.hr/tvrtka/salopek-doo/MMIBQlBY',
        // 'https://www.companywall.hr/tvrtka/aviator-doo/MMIBQq1R',
        // 'https://www.companywall.hr/tvrtka/vinia-catering-jdoo/MMIBQtuC',
        // 'https://www.companywall.hr/tvrtka/vinia-vino-jdoo/MMIBQzo0',
        // 'https://www.companywall.hr/tvrtka/vinia-restoran-jdoo/MMIBt5Dq',
        // 'https://www.companywall.hr/tvrtka/vinia-smjestaj-jdoo/MMIBtBbD',
        // 'https://www.companywall.hr/tvrtka/vinia-camping-jdoo/MMIBtIVY',
        // 'https://www.companywall.hr/tvrtka/limarija-micko-jdoo/MMIBtPPR',
        // 'https://www.companywall.hr/tvrtka/marco-dallara-jdoo/MMIBtUGC',
        // 'https://www.companywall.hr/tvrtka/alibi-jdoo-u-stecaju/MMxUzVtY',
        // 'https://www.companywall.hr/tvrtka/sipus-usluge-jdoo-u-stecaju/MMIBtJ30',
        // 'https://www.companywall.hr/tvrtka/inspira-usluge-jdoo-u-stecaju/MMIBtbwq',
        // 'https://www.companywall.hr/tvrtka/pet-do-pet-jdoo/MMIBtfqD',
        // 'https://www.companywall.hr/tvrtka/petit-marie-doo/MMIBtjjY',
        'https://www.companywall.hr/tvrtka/bozicevic-lana-jdoo/MMIBto8R',
        'https://www.companywall.hr/tvrtka/ra-zz/MMIBtQJC',
        'https://www.companywall.hr/tvrtka/rimos-trgovina-d-o-o/MMIBtyS0',
        'https://www.companywall.hr/tvrtka/vs-trgovina-i-servis-jdoo/MMIBuEIq',
        'https://www.companywall.hr/tvrtka/tune-up-doo/MMIBu9AD',
        'https://www.companywall.hr/tvrtka/mit-10-jdoo/MMIBuH0Y',
        'https://www.companywall.hr/tvrtka/adr-solutions-d-o-o/MMxUzZnR',
        'https://www.companywall.hr/tvrtka/frljak-vlado-jdoo-u-stecaju/MMIBu2QR',
        'https://www.companywall.hr/tvrtka/digitus-movens-jdoo/MMIBuSNC',
        'https://www.companywall.hr/tvrtka/visoka-uciteljska-skola-u-petrinji/MMIBuWg0',
        'https://www.companywall.hr/tvrtka/dom-za-starije-i-nemocne-osobe-ivanic-grad-u-likvidaciji/MMIBuaZq',
        'https://www.companywall.hr/tvrtka/auto1-doo/MMIBusEC',
        'https://www.companywall.hr/tvrtka/azt-pozitiva-doo/MMIBuvv0',
        'https://www.companywall.hr/tvrtka/verona-due-doo/MMIBvxoq',
        'https://www.companywall.hr/tvrtka/unoterm-trta-doo-u-stecaju/MMxUz8DC',
        'https://www.companywall.hr/tvrtka/commit-200-doo/MMIBv7hD',
        'https://www.companywall.hr/tvrtka/home-advice-doo/MMIBvFcY',
        'https://www.companywall.hr/tvrtka/mak-centar-doo/MMIBvLWR',
        'https://www.companywall.hr/tvrtka/makina-trade-jdoo/MMIBv6RC',
        'https://www.companywall.hr/tvrtka/uz-put-j-d-o-o-u-stecaju/MMIBvVH0',
        'https://www.companywall.hr/tvrtka/janika-vrata-j-d-o-o/MMIBvZ3q',
        'https://www.companywall.hr/tvrtka/dj-studen-007-jdoo/MMIBvdyD',
        'https://www.companywall.hr/tvrtka/interijeri-mestrovic-jdoo/MMIBvDrY',
        'https://www.companywall.hr/tvrtka/amber-d-o-o/MMIBvlkR',
        'https://www.companywall.hr/tvrtka/emanuel-i-duje-doo/MMIBvqeC',
        'https://www.companywall.hr/tvrtka/tva-jdoo/MMxUzhb0',
        'https://www.companywall.hr/tvrtka/savaren-trustee-jdoo/MMIBvuY0',
        'https://www.companywall.hr/tvrtka/sailor-expert-doo/MMIBw0Sq',
        'https://www.companywall.hr/tvrtka/charter-profi-trading-doo/MMIBw3KD',
        'https://www.companywall.hr/tvrtka/koverna-usluge-jdoo-u-stecaju/MMIBwC9Y',
        'https://www.companywall.hr/tvrtka/abramovic-uvoz---izvoz--jdoo-u-stecaju/MMIBwKxR',
        'https://www.companywall.hr/tvrtka/agrona-profit-jdoo/MMIBwPtC',
        'https://www.companywall.hr/tvrtka/murgco--j-d-o-o/MMIBwUn0',
        'https://www.companywall.hr/tvrtka/king-tourist-jdoo/MMIBwJgq',
        'https://www.companywall.hr/tvrtka/illy-jdoo-u-stecaju/MMIBwcaD',
        'https://www.companywall.hr/tvrtka/pajo-borota-jdoo-u-stecaju/MMIBwg4Y',
        'https://www.companywall.hr/tvrtka/salihovic-jdoo-u-stecaju/MMxUzN4q',
        'https://www.companywall.hr/tvrtka/jakovac-parking-usluge-jdoo/MMIBwkOR',
        // 'https://www.companywall.hr/tvrtka/kea-enterprises-doo/MMIBwpFC',
        // 'https://www.companywall.hr/tvrtka/blic-doo/MMIBwt50',
        // 'https://www.companywall.hr/tvrtka/institut-za-javno-zasebno-partnerstvo-zavod-turjak/MMIBwyvq',
        // 'https://www.companywall.hr/tvrtka/morosini-jdoo/MMIBy9iY',
        // 'https://www.companywall.hr/tvrtka/magnum-jdoo/MMIByHdR',
        // 'https://www.companywall.hr/tvrtka/filzer-jdoo/MMIByOXC',
        // 'https://www.companywall.hr/tvrtka/planet-shop-doo-u-stecaju/MMIByT60',
        // 'https://www.companywall.hr/tvrtka/bora-yacht-d-o-o/MMIByXHq',
        // 'https://www.companywall.hr/tvrtka/segin-jdoo-u-stecaju/MMxUzrOD',
        // 'https://www.companywall.hr/tvrtka/electrus-j-d-o-o/MMIByb7D',
        // 'https://www.companywall.hr/tvrtka/alkemija-jdoo/MMIByezY',
        // 'https://www.companywall.hr/tvrtka/kujundzic-krbavac-j-d-o-o-u-stecaju/MMIByisR',
        // 'https://www.companywall.hr/tvrtka/terza-j-d-o-o/MMIBynlC',
        // 'https://www.companywall.hr/tvrtka/infinity-karma-j-d-o-o/MMIBysf0',
        // 'https://www.companywall.hr/tvrtka/rituals-jdoo/MMIBywYq',
        // 'https://www.companywall.hr/tvrtka/nemesi-club-j-d-o-o/MMIBz1TD',
        // 'https://www.companywall.hr/tvrtka/erceg-automobili-doo/MMIBzALY',
        // 'https://www.companywall.hr/tvrtka/anchoring-doo/MMIBzGBR',
        // 'https://www.companywall.hr/tvrtka/meus-jdoo/MMIBz21C',
        // 'https://www.companywall.hr/tvrtka/click-d-o-o/MMxUzvFY',
        // 'https://www.companywall.hr/tvrtka/gerizim-jdoo/MMIBz6u0',
        // 'https://www.companywall.hr/tvrtka/barbershop-j-d-o-o/MMIBzVnq',
        // 'https://www.companywall.hr/tvrtka/pavlovic-color-jdoo/MMIBzZDD',
        // 'https://www.companywall.hr/tvrtka/travelis-jdoo/MMIBz8bY',
        // 'https://www.companywall.hr/tvrtka/zorkovic-jdoo/MMIBzhVR',
        // 'https://www.companywall.hr/tvrtka/goya-consulting-jdoo/MMIBzNPC',
        // 'https://www.companywall.hr/tvrtka/zdenko-metali-jdoo/MMIBzrG0',
        // 'https://www.companywall.hr/tvrtka/mare-nauticus-jdoo/MMIBzv5q',
        // 'https://www.companywall.hr/tvrtka/auto-exclusive-plus-doo/MMIC00wD',
        // 'https://www.companywall.hr/tvrtka/mar-nautika-doo/MMIC03qY',
        // 'https://www.companywall.hr/tvrtka/synteks-doo/MMx40x5R',
        // 'https://www.companywall.hr/tvrtka/studio-renata-doo/MMIC0CjR',
        // 'https://www.companywall.hr/tvrtka/avantgarden-jdoo-u-stecaju/MMIC0K8C',
        // 'https://www.companywall.hr/tvrtka/bp-galerija-doo/MMIC0RJ0',
        // 'https://www.companywall.hr/tvrtka/auto-centar-pogacic-doo/MMIC046q',
        // 'https://www.companywall.hr/tvrtka/orlic-doo/MMIC0YID',
        // 'https://www.companywall.hr/tvrtka/granular-grupa-doo/MMIC0dAY',
        // 'https://www.companywall.hr/tvrtka/tisucu-otoka-jdoo/MMIC0D0R',
        // 'https://www.companywall.hr/tvrtka/flsj-trade-doo/MMIC0kQC',
        // 'https://www.companywall.hr/tvrtka/staklo-lak-jdoo/MMIC0pN0',
        // 'https://www.companywall.hr/tvrtka/sapic-gradnja-jdoo/MMIC0tfq',
        // 'https://www.companywall.hr/tvrtka/hermes-promet-doo/MMx403wC',
        // 'https://www.companywall.hr/tvrtka/vedran-1207-jdoo-u-stecaju/MMIC0zZD',
        // 'https://www.companywall.hr/tvrtka/setemana-doo/MMICx5UY',
        // 'https://www.companywall.hr/tvrtka/elektroinstalacije-aleksandar-jdoo/MMICxB2R',
        // 'https://www.companywall.hr/tvrtka/regular-ugostiteljstvo-doo/MMICxICC',
        // 'https://www.companywall.hr/tvrtka/antimar-doo/MMICxPE0',
        // 'https://www.companywall.hr/tvrtka/coloro-leona-jdoo/MMICxTuq',
        // 'https://www.companywall.hr/tvrtka/prestige-travel-doo/MMICxXoD',
        // 'https://www.companywall.hr/tvrtka/zagatne-konstrukcije-jdoo/MMICxbhY',
        // 'https://www.companywall.hr/tvrtka/ftl-service-doo/MMICxfcR',
        // 'https://www.companywall.hr/tvrtka/ured-kk-knjigovodstvo-jdoo/MMICxjWC',
        // 'https://www.companywall.hr/tvrtka/beljo-kljuc-doo-u-stecaju/MMr07Y',
        // 'https://www.companywall.hr/tvrtka/studio-otisak-doo/MM9Yx30',
        // 'https://www.companywall.hr/tvrtka/juzni-vjetar-doo/MMx40Cq0',
        // 'https://www.companywall.hr/tvrtka/cerera-bio-doo/MMICxoR0',
        // 'https://www.companywall.hr/tvrtka/axxxtina-design-jdoo/MMICxQGq',
        // 'https://www.companywall.hr/tvrtka/ferrum-soldus-jdoo/MMICxy3D',
        // 'https://www.companywall.hr/tvrtka/sps-grupa-doo/MMIC11yY',
        // 'https://www.companywall.hr/tvrtka/coco-sport-doo/MMIC1ArR',
        // 'https://www.companywall.hr/tvrtka/ignio-management-doo/MMIC1GkC',
        // 'https://www.companywall.hr/tvrtka/dm-auto-trade-doo-u-stecaju/MMIC12e0',
        // 'https://www.companywall.hr/tvrtka/demolish-and-build-jdoo/MMIC1SJq',
        // 'https://www.companywall.hr/tvrtka/darko-usluge-gradevinskom-mehanizacijom-jdoo-u-stecaju/MMIC1WSD',
        // 'https://www.companywall.hr/tvrtka/lesis-moda-jdoo-u-stecaju/MMx40Kiq',
        // 'https://www.companywall.hr/tvrtka/minimax-doo/MMIC1vgD',
        // 'https://www.companywall.hr/tvrtka/nelany-impex-doo/MMICExaY',
        // 'https://www.companywall.hr/tvrtka/frg-transport-doo-u-stecaju/MMICE74R',
        // 'https://www.companywall.hr/tvrtka/gs-commerce-doo/MMICEFOC',
        // 'https://www.companywall.hr/tvrtka/clean--shine-doo-u-stecaju/MMICELF0',
        // 'https://www.companywall.hr/tvrtka/zlatni-klub-d-o-o/MMICE6Eq',
        // 'https://www.companywall.hr/tvrtka/frutarija-doo/MMx40RdD',
        // 'https://www.companywall.hr/tvrtka/all-d-o-o/MMICE4vD',
        // 'https://www.companywall.hr/tvrtka/lanisce-energija-d-o-o/MMICEYpY',
        // 'https://www.companywall.hr/tvrtka/biuk-usluge-doo/MMICEdiR',
        // 'https://www.companywall.hr/tvrtka/bruno--barbara-doo/MMICEDdC',
        // 'https://www.companywall.hr/tvrtka/silver-moon-doo/MMICElX0',
        // 'https://www.companywall.hr/tvrtka/capital-engineering-doo/MMICEqRq',
        // 'https://www.companywall.hr/tvrtka/gajser-team-243-doo/MMICEuHD',
        // 'https://www.companywall.hr/tvrtka/adriatic-seaside-homes-doo/MMIC507Y',
        // 'https://www.companywall.hr/tvrtka/icbig-company-doo/MMIC55zR',
        // 'https://www.companywall.hr/tvrtka/genio-leopardo-genijalci-doo-u-stecaju/MMIC5BsC',
        // 'https://www.companywall.hr/tvrtka/binom-doo/MMx404XY',
        // 'https://www.companywall.hr/tvrtka/as-sesvete-bus-moslavina-i-posavina-doo/MMIC5Il0',
        // 'https://www.companywall.hr/tvrtka/cbs-international-doo/MMIC5Peq',
        // 'https://www.companywall.hr/tvrtka/vapor-usluge-doo/MMIC5UYD',
        // 'https://www.companywall.hr/tvrtka/verbriefung--co-doo/MMIC5JTY',
        // 'https://www.companywall.hr/tvrtka/mesarstvo-banko-doo/MMIC5cLR',
        // 'https://www.companywall.hr/tvrtka/miva-usluge-doo/MMIC5gBC',
        // 'https://www.companywall.hr/tvrtka/domograd-projekt-doo/MMIC5k10',
        // 'https://www.companywall.hr/tvrtka/ing-commodity-trade-doo/MMIC5otq',
        // 'https://www.companywall.hr/tvrtka/ayc-management-doo/MMIC5QnD',
        // 'https://www.companywall.hr/tvrtka/hema-jdoo/MMIC5yDY',
        // 'https://www.companywall.hr/tvrtka/watermelon-doo/MMx40Y6R',
        // 'https://www.companywall.hr/tvrtka/zvijezda-jdoo/MMIC3EbR',
        // 'https://www.companywall.hr/tvrtka/panther-bau-doo/MMIC39VC',
        // 'https://www.companywall.hr/tvrtka/strujic-sd-jdoo/MMIC3HP0',
        // 'https://www.companywall.hr/tvrtka/mm-interijeri-jdoo-u-stecaju/MMIC3OFq',
        // 'https://www.companywall.hr/tvrtka/moda-in-jdoo-u-likvidaciji/MMIC3T5D',
        // 'https://www.companywall.hr/tvrtka/crazy-cat-jdoo/MMIC3WwY',
        // 'https://www.companywall.hr/tvrtka/lav-jdoo-u-stecaju/MMIC3aqR',
        // 'https://www.companywall.hr/tvrtka/building--construct-jdoo/MMIC3ejC',
        // 'https://www.companywall.hr/tvrtka/bont-jdoo/MMIC3i80',
        // 'https://www.companywall.hr/tvrtka/trgovina-tina-jdoo/MMIC3nXq',
        // 'https://www.companywall.hr/tvrtka/spark-doo/MMx40dIC',
        // 'https://www.companywall.hr/tvrtka/imdigital-jdoo-u-stecaju/MMIC3s6D',
        // 'https://www.companywall.hr/tvrtka/proelium-jdoo/MMIC3wIY',
        // 'https://www.companywall.hr/tvrtka/adaptacija-stanova-ravlic-jdoo/MMIC71AR',
        // 'https://www.companywall.hr/tvrtka/genesis-group-jdoo/MMIC7A0C',
        // 'https://www.companywall.hr/tvrtka/struja-tdi-jdoo/MMIC7FQ0',
        // 'https://www.companywall.hr/tvrtka/puskadija-auto-jdoo/MMIC7Llq',
        // 'https://www.companywall.hr/tvrtka/tekstil-vienna-jdoo/MMIC76fD',
        // 'https://www.companywall.hr/tvrtka/hadax-tuning-jdoo/MMIC7VZY',
        // 'https://www.companywall.hr/tvrtka/elektro-teh-kusan-jdoo/MMIC7ZUR',
        // 'https://www.companywall.hr/tvrtka/inoterm-instalacije-jdoo/MMIC782C',
        // 'https://www.companywall.hr/tvrtka/q-bit-doo/MMx40DA0',
        // 'https://www.companywall.hr/tvrtka/tvornica-glazbe-jdoo/MMIC7hC0',
        // 'https://www.companywall.hr/tvrtka/tuckoric-rdm-jdoo/MMIC7N1q',
        // 'https://www.companywall.hr/tvrtka/svedobro-i-pozitivno-jdoo/MMIC7quD',
        // 'https://www.companywall.hr/tvrtka/blic-promet-jdoo-u-stecaju/MMIC7uoY',
        // 'https://www.companywall.hr/tvrtka/tmb-doo/MMICA0hR',
        // 'https://www.companywall.hr/tvrtka/car-delivery-doo/MMICA3cC',
        // 'https://www.companywall.hr/tvrtka/ska-usluge-i-proizvodnja-jdoo/MMICACW0',
        // 'https://www.companywall.hr/tvrtka/podorad-ing-zlatko-jdoo/MMICAKPq',
        // 'https://www.companywall.hr/tvrtka/zaprega-jdoo-u-stecaju/MMICARGD',
        // 'https://www.companywall.hr/tvrtka/selidbe-vidovic-jdoo/MMICA43Y',
        // 'https://www.companywall.hr/tvrtka/south-trade-doo/MMx40kzq',
        // 'https://www.companywall.hr/tvrtka/goran-zecevic-jdoo/MMICAJyR',
        // 'https://www.companywall.hr/tvrtka/gb-projekt-doo/MMICAgk0',
        // 'https://www.companywall.hr/tvrtka/novi-uskok-65-jdoo/MMICAk8q',
        // 'https://www.companywall.hr/tvrtka/mjernica-jdoo/MMICApJD',
        // 'https://www.companywall.hr/tvrtka/adriatic-trip-jdoo-u-stecaju/MMICAtSY',
        // 'https://www.companywall.hr/tvrtka/vlahinic-dubrovnik-jdoo/MMICAzKR',
        // 'https://www.companywall.hr/tvrtka/pemo-nekretnine-doo/MMIC959C',
        // 'https://www.companywall.hr/tvrtka/naomi-apartments-jdoo/MMIC9Bx0',
        // 'https://www.companywall.hr/tvrtka/jtd-logistic-doo/MMIC9HQq',
        // 'https://www.companywall.hr/tvrtka/tehnum-doo/MMx40psD',
        // 'https://www.companywall.hr/tvrtka/illyrian-yachting-doo/MMIC9OND',
        // 'https://www.companywall.hr/tvrtka/hoora-doo/MMIC9TgY',
        // 'https://www.companywall.hr/tvrtka/za-korak-vise-jdoo/MMIC9XaR',
        // 'https://www.companywall.hr/tvrtka/ad-auto-doo/MMIC9b4C',
        // 'https://www.companywall.hr/tvrtka/nova-wood-jdoo/MMIC9fO0',
        // 'https://www.companywall.hr/tvrtka/pavan-doo/MMIC9jCq',
        // 'https://www.companywall.hr/tvrtka/mar-appart-d-o-o/MMIC9oED',
        // 'https://www.companywall.hr/tvrtka/autotaksi-novalja-nevia-j-d-o-o/MMIC9svY',
        // 'https://www.companywall.hr/tvrtka/immortelle-events-doo/MMIC9wpR',
        // 'https://www.companywall.hr/tvrtka/maglica-pvc-stolarija-jdoo-u-stecaju/MMICB1iC',
        // 'https://www.companywall.hr/tvrtka/metal-invest-doo-u-stecaju/MMx40tlY',
        // 'https://www.companywall.hr/tvrtka/fm-project-d-o-o/MMICBAd0',
        // 'https://www.companywall.hr/tvrtka/ivankovic-nekretnine-doo/MMICBGWq',
        // 'https://www.companywall.hr/tvrtka/vektis-jdoo/MMICB2RD',
        // 'https://www.companywall.hr/tvrtka/martronik-jdoo/MMICBSHY',
        // 'https://www.companywall.hr/tvrtka/drustvo-u-prirodi-d-o-o/MMICBW7R',
        // 'https://www.companywall.hr/tvrtka/mio-car-jdoo-u-stecaju/MMICBZzC',
        // 'https://www.companywall.hr/tvrtka/ego-sum-revera-jdoo/MMICB8s0',
        // 'https://www.companywall.hr/tvrtka/audax-real-estate-doo/MMICBhkq',
        // 'https://www.companywall.hr/tvrtka/golden-island-doo/MMICBNeD',
        // 'https://www.companywall.hr/tvrtka/tehnoline-telekom-doo/MMICBrYY',
        // 'https://www.companywall.hr/tvrtka/tiora-d-o-o/MM9Y3wq',
        // 'https://www.companywall.hr/tvrtka/zag-auto-doo/MMx40zfR',
        // 'https://www.companywall.hr/tvrtka/new-hempage-jdoo/MMICBvTR',
        // 'https://www.companywall.hr/tvrtka/radiocomm-emq-doo/MMICCxLC',
        // 'https://www.companywall.hr/tvrtka/energetics-doo/MMICC7B0',
        // 'https://www.companywall.hr/tvrtka/stardust-usluge-jdoo/MMICCFxq',
        // 'https://www.companywall.hr/tvrtka/kros-doo/MMICCKtD',
        // 'https://www.companywall.hr/tvrtka/sportstar-doo/MMICCRnY',
        // 'https://www.companywall.hr/tvrtka/vvd-doo/MMICC4DR',
        // 'https://www.companywall.hr/tvrtka/bicko-jdoo-u-stecaju/MMICCYbC',
        // 'https://www.companywall.hr/tvrtka/bumblebee-yachting-doo/MMICCdV0',
        // 'https://www.companywall.hr/tvrtka/bateau-yachting-doo/MMICCDOq',
        // 'https://www.companywall.hr/tvrtka/mativa-2000-doo/MMx4x5ZC',
        // 'https://www.companywall.hr/tvrtka/art-consulting-doo/MMICClFD',
        // 'https://www.companywall.hr/tvrtka/pravo-mjesto-doo/MMICCq5Y',
        // 'https://www.companywall.hr/tvrtka/ziba-putnik-jdoo/MMICCtwR',
        // 'https://www.companywall.hr/tvrtka/lim-is-jdoo/MMICCzqC',
        // 'https://www.companywall.hr/tvrtka/finesa-grupa-doo/MMICF5j0',
        // 'https://www.companywall.hr/tvrtka/lira-consulting-doo/MMICFBdq',
        // 'https://www.companywall.hr/tvrtka/frigo-artis-jdoo/MMICFIXD',
        // 'https://www.companywall.hr/tvrtka/roza-vrpca-jdoo/MMICFP6Y',
        // 'https://www.companywall.hr/tvrtka/vam-invent-doo/MMICFUIR',
        // 'https://www.companywall.hr/tvrtka/architecture-web-design-istra-doo/MMICFJAC',
        // 'https://www.companywall.hr/tvrtka/frane-voce-jdoo/MMx4xBU0',
        // 'https://www.companywall.hr/tvrtka/funky-food-doo/MMICFc00',
        // 'https://www.companywall.hr/tvrtka/wellness--fitness-life-jdoo-u-stecaju/MMICFfsq',
        // 'https://www.companywall.hr/tvrtka/medena-burza-doo/MMICFjlD',
        // 'https://www.companywall.hr/tvrtka/andrijans-logistika-doo-u-stecaju/MMICFofY',
        // 'https://www.companywall.hr/tvrtka/dom-produkt-jdoo-u-stecaju/MMICFQZR',
        // 'https://www.companywall.hr/tvrtka/bpm-domus-jdoo-u-stecaju/MMICFyUC',
        // 'https://www.companywall.hr/tvrtka/time-to-be-doo/MMICGE20',
        // 'https://www.companywall.hr/tvrtka/3ls-live-doo/MMICG9Bq',
        // 'https://www.companywall.hr/tvrtka/full-faktor-jdoo/MMICGH1D',
        // 'https://www.companywall.hr/tvrtka/kv-zg-gradnja-jdoo/MMICG2uY',
        // 'https://www.companywall.hr/tvrtka/euro---cars-plus-doo-u-stecaju/MMx4xILq',
        // 'https://www.companywall.hr/tvrtka/visinski-radovi-doo/MMICGSoR',
        // 'https://www.companywall.hr/tvrtka/armanteh-jdoo/MMICGWhC',
        // 'https://www.companywall.hr/tvrtka/more-i-sport-jdoo/MMICGac0',
        // 'https://www.companywall.hr/tvrtka/pick--roll-jdoo/MMICGeVq',
        // 'https://www.companywall.hr/tvrtka/herrmann-doo/MMICGiPD',
        // 'https://www.companywall.hr/tvrtka/napi-trade-doo/MMICGnGY',
        // 'https://www.companywall.hr/tvrtka/dom-ideja-doo/MMICGs3R',
        // 'https://www.companywall.hr/tvrtka/vlatusa-usluge-jdoo/MMICGvyC',
        // 'https://www.companywall.hr/tvrtka/festival-and-family-travel-doo/MMICHxr0',
        // 'https://www.companywall.hr/tvrtka/mala-proizvodnja-jdoo/MMICH7jq',
        // 'https://www.companywall.hr/tvrtka/inter---moneta-d-o-o/MMx4xPBD',
        // 'https://www.companywall.hr/tvrtka/welding-point-doo/MMICHF8D',
        // 'https://www.companywall.hr/tvrtka/lancer-technology-doo/MMICHLJY',
        // 'https://www.companywall.hr/tvrtka/otok-bk-jdoo-u-stecaju/MMICH6SR',
        // 'https://www.companywall.hr/tvrtka/auto-mile-jdoo/MMICHVKC',
        // 'https://www.companywall.hr/tvrtka/zagi-doo/MMICHZ90',
        // 'https://www.companywall.hr/tvrtka/organic-collard-greens-jdoo/MMICH80q',
        // 'https://www.companywall.hr/tvrtka/king-color-jdoo/MMICHDQD',
        // 'https://www.companywall.hr/tvrtka/mardas-kvadrat-doo/MMx4xU1Y',
        // 'https://www.companywall.hr/tvrtka/mini-mont-jdoo/MMICI32q',
        // 'https://www.companywall.hr/tvrtka/kl-adepto-doo/MMICICCD',
        // 'https://www.companywall.hr/tvrtka/rari-jdoo/MMICIKEY',
        // 'https://www.companywall.hr/tvrtka/th-morgan-jdoo/MMICIPvR',
        // 'https://www.companywall.hr/tvrtka/eds-doo/MMICIUpC',
        // 'https://www.companywall.hr/tvrtka/victory-organics-doo/MMICIJi0',
        // 'https://www.companywall.hr/tvrtka/rjesenja-buducnosti-doo/MMICIccq',
        // 'https://www.companywall.hr/tvrtka/igor-2000-doo/MMICIgWD',
        // 'https://www.companywall.hr/tvrtka/gre-jdoo-u-stecaju/MMICIkRY',
        // 'https://www.companywall.hr/tvrtka/transportni-konzultanti-drustvo-s-ogranicenom-odgovornoscu-za-prijevoz-trgovinu-putnicke-agencije-po/MMx4xXuR',
        // 'https://www.companywall.hr/tvrtka/cars--cars-jdoo/MMICIpHR',
        // 'https://www.companywall.hr/tvrtka/scan-sled-doo/MMICIt7C',
        // 'https://www.companywall.hr/tvrtka/pgm-real-estate-doo/MMICIyz0',
        // 'https://www.companywall.hr/tvrtka/trust-advisor-doo/MMICKErq',
        // 'https://www.companywall.hr/tvrtka/maslina-j-d-o-o/MMICK9kD',
        // 'https://www.companywall.hr/tvrtka/nova-gradnja-j-d-o-o/MMICKHeY',
        // 'https://www.companywall.hr/tvrtka/m2-projekt-d-o-o/MMICKOYR',
        // 'https://www.companywall.hr/tvrtka/like-barovi-j-d-o-o-u-stecaju/MMICKTTC',
        // 'https://www.companywall.hr/tvrtka/de-luxe-company-jdoo/MMICKXL0',
        // 'https://www.companywall.hr/tvrtka/auto-servis-solic-jdoo/MMICKb9q',
        // 'https://www.companywall.hr/tvrtka/peta-dimenzija-doo/MMx4xboC',
        // 'https://www.companywall.hr/tvrtka/auto-traffic-j-d-o-o/MMICKfxD',
        // 'https://www.companywall.hr/tvrtka/izvan-okvira-jdoo/MMICKitY',
        // 'https://www.companywall.hr/tvrtka/d-klaric-jdoo-u-stecaju/MMICKnnR',
        // 'https://www.companywall.hr/tvrtka/dalmatinska-eufemia-charter-doo/MMICKsDC',
        // 'https://www.companywall.hr/tvrtka/o-da-interijeri-j-d-o-o/MMICKwb0',
        // 'https://www.companywall.hr/tvrtka/villa-lavanda-d-o-o/MMICL14q',
        // 'https://www.companywall.hr/tvrtka/josephson-charter-doo/MMICLAOD',
        // 'https://www.companywall.hr/tvrtka/pilana-devcic-d-o-o/MMICLGFY',
        // 'https://www.companywall.hr/tvrtka/as-automobili-d-o-o/MMICL25R',
        // 'https://www.companywall.hr/tvrtka/auto-premier-doo/MMICL6wC',
        // 'https://www.companywall.hr/tvrtka/fillar-doo/MMx4xfh0',
        // 'https://www.companywall.hr/tvrtka/grim-caffe-jdoo-u-stecaju/MMICLVq0',
        // 'https://www.companywall.hr/tvrtka/memoria-jdoo/MMICLZiq',
        // 'https://www.companywall.hr/tvrtka/luna-turizam-doo/MMICL8dD',
        // 'https://www.companywall.hr/tvrtka/morus-doo/MMICLhXY',
        // 'https://www.companywall.hr/tvrtka/pejo-doo/MMICLN6R',
        // 'https://www.companywall.hr/tvrtka/adriatic-wind-doo/MMICLrIC',
        // 'https://www.companywall.hr/tvrtka/lika-grad-jdoo/MMICLvA0',
        // 'https://www.companywall.hr/tvrtka/via-regia-jdoo/MMIC20zq',
        // 'https://www.companywall.hr/tvrtka/laganim-korakom-doo-u-stecaju/MMIC23sD',
        // 'https://www.companywall.hr/tvrtka/spektor-lumani-doo/MMIC2ClY',
        // 'https://www.companywall.hr/tvrtka/senectus-usluge-doo/MMx4xjbq',
        // 'https://www.companywall.hr/tvrtka/hero-eisen--doo-u-stecaju/MMIC2KfR',
        // 'https://www.companywall.hr/tvrtka/d-sport-international-consulting-doo/MMIC2RZC',
        // 'https://www.companywall.hr/tvrtka/usluge-milinovic-jdoo/MMIC24U0',
        // 'https://www.companywall.hr/tvrtka/green-tipi-travel-doo/MMIC2YLq',
        // 'https://www.companywall.hr/tvrtka/volley-soft-doo/MMIC2dBD',
        // 'https://www.companywall.hr/tvrtka/mak-management-international-doo/MMIC2D1Y',
        // 'https://www.companywall.hr/tvrtka/katalpa-produkcija-jdoo/MMIC2kuR',
        // 'https://www.companywall.hr/tvrtka/elf-mont-bau-doo/MMIC2poC',
        // 'https://www.companywall.hr/tvrtka/nortpack-doo/MMIC2th0',
        // 'https://www.companywall.hr/tvrtka/layage-jdoo/MMIC2zbq',
        // 'https://www.companywall.hr/tvrtka/retel-doo/MM9YCqD',
        // 'https://www.companywall.hr/tvrtka/krusko-doo/MMx4xoVD',
        // 'https://www.companywall.hr/tvrtka/lani-knezevic-jdoo/MMICO5VD',

        ]); // works
    // let proxyConfig = {
    //     useApifyProxy: true,
    //     apifyProxyGroups: ["RESIDENTIAL"],
    //     apifyProxyCountry: "IE",
    // };
    }else{
        let { proxyConfig } = input;
         requestList = await handleInput(input);
          proxyConfiguration = await Apify.createProxyConfiguration(
        proxyConfig
    );
    }

    

    const requestQueue = await Apify.openRequestQueue();

    logInfo("ABOUT TO SPIT THE INPUT");

    logInfo("ABOUT TO START");
    const crawler = new Apify.PuppeteerCrawler({
        requestList,
        requestQueue,
        maxRequestRetries: 2,
        useSessionPool: true,

        // sessionPoolOptions: { maxPoolSize: 1 },
        // Overrides default Session pool configuration
        sessionPoolOptions: {
            maxPoolSize: 100,
        },
        preNavigationHooks: [
            async (crawlingContext, gotoOptions) => {
                // const { page } = crawlingContext;
                // await page.evaluate((attr) => { window.foo = attr; }, 'bar');
                gotoOptions.waitUntil = 'networkidle2'
            },
        ],
        persistCookiesPerSession: true,
        maxConcurrency: 5,
        proxyConfiguration,

        launchContext: {
            // Chrome with stealth should work for most websites.
            // If it doesn't, feel free to remove this.
            useChrome: true,
            stealth: true,
            launchOptions: {
                // headless: true,
                waitForNetwork: "networkidle0",
                waitUntil: 'networkidle0',
            },
        },
        browserPoolOptions: {
            // This allows browser to be more effective against anti-scraping protections.
            // If you are having performance issues try turning this off.
            // useFingerprints: true,
        },
        navigationTimeoutSecs: 30000,

        handlePageFunction: async (context) => {
            const {
                url,
                userData: { label },
            } = context.request;
            // await context.page.waitForNavigation({waitUntil: 'domcontentloaded', timeout: 60000} )
            // await page.context.page.waitForNetworkIdle
            // await context.page.setDefaultNavigationTimeout(60000);

            // logInfo("Page opened.", { label, url });
            // logInfo("Proxy details")
            // logInfo(context.proxyInfo)
            // logInfo('End of proxy details')
            // logInfo('sessions')
            // logInfo(context.session.sessionPool.config)
            // logInfo(context.session)
            // logInfo('end of session data')
            switch (label) {
                case "LIST":
                    return handleList(context, requestQueue);
                case "DETAIL":
                    return handleDetail(context, requestQueue);
                case "DIRECTOR_PAST_COMPANIES":
                    return handleDirector(context, requestQueue);
                case "SITEMAP":
                    logInfo("sitemap");
                    return handleSitemap(context, requestQueue);
                default:
                    return handleStart(context, requestQueue);
            }
        },
        handleFailedRequestFunction(HandleFailedRequest) {
            console.error(
                "ERRROR IN HANDLE FAILED REQUEST FUNCTION CHANING SESSION"
            );
            try {
                console.error(HandleFailedRequest.error);
                HandleFailedRequest.session.retire();
            } catch (e) {
                console.error(
                    "ERROR CANT ACCESS SESSION FROM HANDLE FAILED REQUEST FUNCTION"
                );
            }
        },
    });

    log.info("Starting the crawl.");
    await crawler.run();
    // TODO put the stats here -
    log.info("Crawl finished.");
});

// this is used to handle in put from apify console
async function handleInput(input, requestQueue) {
    let {
        startUrls,
        sitemap,
        OIB,
        OIBs,
        MBS,
        MBSs,
        SearchTermSearch,
        SearchTerms,
        PastDirectors,
    } = input;
    //newish
    this.scrapDirectors = PastDirectors;

    // sitemap = 'url'
    // startUrls = ['https://www.companywall.hr/sitemap/companies?p=725']

    if (sitemap) {
        // return await getUrlsFromSitemap(sitemapURL);
        // return await Apify.openRequestList("start-urls", [{url: startUrls, userData: {label: "SITEMAP"}}]);
        logInfo(`---------SITEMAP SCRAPER STARTER ----------------------`);
        logInfo(startUrls);
        const requestList = await Apify.RequestList.open(null, [
            {
                requestsFromUrl: "https://www.brewbound.com/sitemap.xml",
                regex: ".*",
            },
        ]);
        logInfo(requestList);
        return requestList;
        //         return await Apify.openRequestList('sitemap', [
        //             {url: startUrls[0].url, userData: {label: "SITEMAP"}}
        //         ])
        //SITEMAP
    } else if (OIB) {
        // scraping OIB for search
        //TODO not implmeneted
    } else if (MBS) {
        // scraping MBS for search
        //TODO not implmeneted
    } else if (SearchTermSearch) {
        // scraping search terms for search
        //TODO not implmeneted
    } else if (typeof startUrls !== "undefined") {
        if (startUrls.length > 0 || !startUrls[0] == "https://example.com/") {
            return await Apify.openRequestList("start-urls", startUrls);
        } else {
            // this is also for local dev as default start array is example.com
            return await Apify.openRequestList("start-urls", [
                "https://www.companywall.hr/tvrtka/timgraf-media-doo/MMxqbQiY",
            ]); // works
        }
    } else {
        // for local dev
        return await Apify.openRequestList("start-urls", [
            "https://www.companywall.hr/tvrtka/timgraf-media-doo/MMxqbQiY",
        ]); // works
        // const requestList = await Apify.openRequestList('start-urls', [{url: 'https://www.companywall.hr/tvrtka/timgraf-media-doo/MMxqbQiY/osobe/PP1158039', userData: {label: "DIRECTOR_PAST_COMPANIES"}}]);
    }
}

async function getUrlsFromSitemap(url, regex) {
    return await RequestList.open(null, [
        {
            requestsFromUrl: "url",
        },
    ]);
}

logInfo("STATS");
logInfo(this.stats);

